### ISSUE TITLE
Double Spinners

### ISSUE THREAD

**Issue by justinferrell** [hariettem/Artemis#100]
**Describe the bug**
If you perform a pull to refresh very slowly, you're able to see that there are actually two spinners that are slightly different in appearance. I'm guessing one of these is the system spinner and one of these is the custom UI that the app is using to show the loading state. 

**To Reproduce**
1. Go to a magazine 
2. Perform a pull to refresh but do so very slowly

**Expected behavior**
I think the ideal behavior would probably be to just use the system spinner and not to actually use the custom one. At the very least, maybe make the custom one match the system spinner?

**Screenshots**
https://github.com/hariettem/Artemis/assets/1128985/7d95b00c-11be-40ab-9036-a8300b15c852

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16

**Comment by RheingoldRiver** [comment]
this is likely the same issue as #57, and it's not android only

**Comment by hariettem** [comment]
Fixed
