### ISSUE TITLE
Votes/boost on comment replies do not register.

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#101]
**Describe the bug**
Unsure if this is a duplicate post. 

Interacting with replies to parent comments throws an error, which ever of the three options you choose. Also occurs on long press menu. 

**To Reproduce**
1. Go to reply to a comment. 
2. Swipe or long press.
3. Interact with voting choices. 
4. Vote at first goes through but shows error after a second or two. 

**Expected behavior**
Function as described. Being able to vote. 

**Screenshots**
https://github.com/hariettem/Artemis/assets/83763643/44fda30c-7991-47d2-823b-a2e85da7823c

**Comment by hariettem** [comment]
@lvndr-dev  This is a kbin.social issue. Going to another instance "fixes" the issue. Can you verify that you get the same error on web? If so, file a bug with kbin?

**Comment by lvndr-dev** [comment]
@hariettem the votes didn't appear to go through [at all.](https://kbin.social/m/ArtemisAppPlayground/t/117402/Testing-image-links#entry-comment-462077)

What exactly do you mean, another instance? Magazine, or go via kbin.cafe?

**Comment by pvmzqahgyd** [comment]
I'm seeing the same issue. No such errors on the web. It's very random too but I narrowed it down a bit. I think that it may have something to do with the slowness of the kbin servers because if I go slower it works better. So for example, if I start scrolling and upvoting multiple comments within a very short period of time, it starts throwing out errors. If I upvote one and give it time, then do another, it fails a lot less often. Perhaps something is timing out?

**Comment by hariettem** [comment]
I find voting on child comments doesn't work on web for me, 80% of the times.

@pvmzqahgyd but interesting. I'll take a look and double check that.

**Comment by lvndr-dev** [comment]
> If I upvote one and give it time, then do another, it fails a lot less often.

> I find voting on child comments doesn't work on web for me, 80% of the times.

In this [video](https://github-production-user-asset-6210df.s3.amazonaws.com/83763643/250085522-44fda30c-7991-47d2-823b-a2e85da7823c.MOV) I purposely gave it some time, and I have taken more time in between upvote attempts before recording - on another post. 

It's just the child comments that won't accept my internet currency of upvotes, no matter what timing I use. I do not have the same issue on web on kbin.social, across magazines.

**Comment by pvmzqahgyd** [comment]
Might be related to #74

**Comment by hariettem** [comment]
FOUND THE BUG! Kbin has a bug when you try to vote a comment using the direct link for it.

Find a subcomment, click more, click copy url. 

Then go to said url and try to vote on it. It fails :)

**Comment by hariettem** [comment]
Artemis uses that link to locate the comment directly. So kbin needs to fix that. But I can work around that... let me see what I can come up with.

**Comment by hariettem** [comment]
Still working on this. Improve something... but there's this weirdness that's ugh.

API should be nearing completion. So once that's done, this should be fixed.

**Comment by mjnhbg3** [comment]
I noticed that voting from the “activity” link instead of directly from the thread/comment url seems to let the vote go through.
