### ISSUE TITLE
User uploaded image not showing

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#102]
**Describe the bug**
User uploaded image is visible on kbin web app, but not in Artemis. 

**Screenshots**

![image](https://github.com/hariettem/Artemis/assets/83763643/321581eb-5c13-48e8-b760-935387dfdc5f)

![image](https://github.com/hariettem/Artemis/assets/83763643/aa68b29f-946a-4e8b-841c-b841f9d410b0)

**Comment by lvndr-dev** [comment]
My bug was related to a comment, but if the main image also isn't visible then it's a way bigger issue.

**Comment by hariettem** [comment]
fixed
