### ISSUE TITLE
Accessible Alt Text Button

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#103]
**Is your feature request related to a problem? Please describe.**
Not everyone's eyesight is the same. Alt texts are available to make images accessible for people with sight issues. 

**Describe the solution you'd like**
Kbin has alt text features for media content. Place an 'alt' button to reveal the image description. Mastodon app does this. 

**Additional context**

![image](https://github.com/hariettem/Artemis/assets/83763643/d89837e2-1c85-4898-b920-20caf5a258cc)

**Comment by hariettem** [comment]
added
