### ISSUE TITLE
Haptics toggle

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#106]
On some Android devices, the default vibration strength is rather high. Strong enough to be annoying while using the app. Also, some people may just not want haptics regardless of vibration strength or device.

**Describe the solution you'd like**
A toggle for haptics in the settings.

**Describe alternatives you've considered**
A more granular haptics setting that changes the vibration strength from none to the strongest setting, and multiple toggles for when haptics should happen (e.g. all interactions, voting, boosting, etc.).

**Comment by lvndr-dev** [comment]
+1, and in my opinion the haptics should have a dedicated menu in the settings. Interesting to know Android has differences for default vibration strength, making personalization all the more important. 

This issue has been [mentioned in the ui/ux channel](https://discord.com/channels/1118996335119569036/1123262197636800562/1124068442639716473), and @hariettem proposed a default, simple option for basic use. 

![image](https://github.com/hariettem/Artemis/assets/83763643/1cf5326f-d697-43db-a4ea-b40b849959cd)

**Comment by win8linux** [comment]
The default haptics on Android devices varies based on the manufacturer's settings, vibration motor, and to some extent even how a device is built.

**Comment by Alaric323** [comment]
Just started the beta, this was the first thing I noticed.  Basically everything you touch does a quarter-ish second vibration on an S23 Ultra.  I would prefer it be more like a keyboard tap which is much faster, and a menu for customization would be nice.

**Comment by Trez-zerT** [comment]
I think it is very important that users be able to completely disable haptics. Even mild haptics and be uncomfortable for arthritic or otherwise sensitive hands.

**Comment by Alaric323** [comment]
This has been implemented, so maybe close the issue for cleanliness purposes?
