### ISSUE TITLE
Tapping on user's thumbnail collapses comment instead of opening user profile

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#107]
When you are within a post and tap on a user's avatar, it collapses their comment. Tapping on the username itself opens the user profile. Not sure if a bug or a feature, expected behavior for me is that tapping on the user avatar would open their profile. Perhaps comments can be collapsed when user taps on the area that extends beyond the username.
EDIT: in addition to the above tapping on user's thumbnail when they made a post takes you to the post itself.

**Comment by hariettem** [comment]
fixed for next update
