### ISSUE TITLE
Parts of the UI flash to light mode while switching back to app

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#108]
**Describe the bug**
Some parts of the user interface briefly change to light mode when switching back to the app in dark mode.

**To Reproduce**
1. Open Artemis
2. Switch to another application
3. Switch back to Artemis
4. See very brief partial UI mode change

**Expected behavior**
App fully retains dark mode when switching back to it.

**Screenshots/Recordings**
![image](https://github.com/hariettem/Artemis/assets/11584387/b617742e-892c-44ad-9571-f8a7d7207ce5)
![image](https://github.com/hariettem/Artemis/assets/11584387/fceb3890-6f1d-45ee-b4a5-96be14ef7ded)

https://github.com/hariettem/Artemis/assets/11584387/a659d754-0378-458a-a32c-d803be737bcc

https://github.com/hariettem/Artemis/assets/11584387/c8eccb79-8980-4865-8a90-1904d91b313a

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 15.7.6
 - Version: 0.1.2/`2dbff580-2f3f-4ccd-86bb-f3a48fe116ee`

**Additional context**
May require multiple attempts to reproduce

**Comment by win8linux** [comment]
Still occurs as of update `f9c7f120-140b-494f-bde1-1dbae21b8717`.

**Comment by pvmzqahgyd** [comment]
Seeing it here too iPhone 13 Pro iOS 16.5.1

**Comment by hariettem** [comment]
I saw it once but couldn't repro... but got an idea on how to mitigate this

**Comment by hariettem** [comment]
does this still repro? if so, pls reopen
