### ISSUE TITLE
When logged out, the upvote/downvote containers are accessibile but empty

### ISSUE THREAD

**Issue by RheingoldRiver** [hariettem/Artemis#11]
**Describe the bug**
When a user is logged out & swipes a post to the left to interact with it (upvote/downvote), they're presented with two empty rectangles, one blue, one orange.

**To Reproduce**
1. Log out
2. Swipe left on a post
3. Observe the empty rectangles.

**Expected behavior**
Honestly, not sure. There's a couple options that I can think of right now.

1. Disable swiping for logged-out users
2. On swipe, show a pop-up saying "Log in to vote!" (might be annoying but at least there's a feedback for swiping)
3. Show no-entry signs in each of the rectangles
4. Show a single greyed-out rectangle with a no-entry sign
5. Show a single greyed-out rectangle that's the width of the two current rectangles combined, containing a no-entry sign

**Screenshots**
It's this but when you're logged out (I'd rather not retype my pw atm):
![image](https://github.com/hariettem/Artemis/assets/18037011/3e7642aa-f56c-4038-9181-c4246a511050)

**Smartphone (please complete the following information):**
* Device: Samsung Galaxy 9
* OS: Android 10
* Version alpha.1

**Comment by RheingoldRiver** [comment]
Note: 190 is NOT related. I made a mistake.

**Comment by mincedog** [comment]
When you are logged out and try to interact to a post it says problem voting I think the error message should say login to interact

**Comment by hariettem** [comment]
actions disabled when logged out
