### ISSUE TITLE
Copy app details

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#110]
With the advent of OTA updates, it has become necessary to include both the app version and the update version in reports. Copying the latter is very cumbersome, since it is a long alphanumeric string with dashes.

**Describe the solution you'd like**
Tap and holding on the app details at the bottom of the Settings view copies the app version, channel (maybe later on), and update version to the clipboard.

**Describe alternatives you've considered**
Same as above, but just tapping to copy.

**Additional context**
Tap and holding in this area to copy the info in it:
![image](https://github.com/hariettem/Artemis/assets/11584387/3fd99aca-1291-468a-a506-c50a7b8a6b9e)

**Comment by hariettem** [comment]
done
