### ISSUE TITLE
Ambiguous subscribe button in Magazines

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#112]
It's rather hard to tell whether user is subscribed or not based on the icon alone. Perhaps a checkmark or a word instead? In addition to that, there is no notification when tapping on the button indicating confirmation. 

<img width="448" alt="Screenshot 2023-07-01 at 6 24 02 AM" src="https://github.com/hariettem/Artemis/assets/77108475/be295b45-3133-4d0b-94b3-095f4912729e">

**Comment by lvndr-dev** [comment]
https://github.com/hariettem/Artemis/issues/113#issuecomment-1614999630

Same answer I'll give here: UI/UX is not set in stone as is. This issue will need a redesign some point in the future.

**Comment by pvmzqahgyd** [comment]
Yes sure thing, the effort is to collect suggestions for those future redesigns yes?

**Comment by lvndr-dev** [comment]
Definitely, though I will say: we are using Apollo as a guideline, so design choices you've seen there are likely to appear in Artemis's releases.

**Comment by hariettem** [comment]
Fixed with new magazine menu and sidebar
