### ISSUE TITLE
Decrease indentation for comments & change color palette

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#113]
I noticed that comments are indented quite a lot and we run out of screen space relatively quickly. Compared to Memmy and Apollo, current Artemis design has much larger indentations. The color palette for Artemis is also quite muted, brighter colors work better  think. 

![IMG_2013](https://github.com/hariettem/Artemis/assets/77108475/77f13266-7ff4-4726-a4f7-991155bf1427)

![IMG_2014](https://github.com/hariettem/Artemis/assets/77108475/558f4635-04b6-4643-95bd-81d99624538f)

<img width="448" alt="Screenshot 2023-07-01 at 6 22 40 AM" src="https://github.com/hariettem/Artemis/assets/77108475/ea279f0b-05c2-43c7-ab61-fc921aa4fda8">

**Comment by lvndr-dev** [comment]
UI and UX design will be expanded upon in the following cycles, I presume. 
I have proposed an Apollo-like design which would deal with text display, as well as color schemes. My suggestion was also to have customization options readily accessible. 

> Compared to Memmy
Could you share a screenshot of Memmy? I'd like to see how they handle some things.

**Comment by pvmzqahgyd** [comment]
@lvndr-dev Memmy is the 1st screenshot

**Comment by hariettem** [comment]
decreased indentation on next update. Color theming later. But if y'all wanna give me more visible colors for now. Drop em below.

These are the ones used now (depth 1 to 6)
```
  '#732982',
  '#24408E',
  '#008026',
  '#FFED00',
  '#FF8C00',
  '#E40303',
```

**Comment by lvndr-dev** [comment]
> Drop em below.

@hariettem 

![image](https://github.com/hariettem/Artemis/assets/83763643/5e26f6fa-5f1b-4f91-890c-e3bed12b627d)
```
// Artemis Styles
Rainbow
['#e40303','#ff8c00','#ffed00','#008026','#12605a','#24408e','#732982']

Artemis
['#622c7c','#9342ba','#c358f8','#7835ff','#9a68ff','#bc9aff','#e6e6fa']

Devilry
['#ff36f9','#eb36fd','#d136fd','#9f36fd','#6d36fd','#5436fd','#3b36fd']

kbin
['#5a28c0','#7835ff','#9743fd','#b550fa','#c358f8','#db7cd4','#f2a0af']

kmoon
['#c0a6e3','#9966cc','#4e0283','#2e3192','#1e9cd7','#ed1c24','#f68e92']

Lavender
['#cc66cc','#c066cc','#b366cc','#9966cc','#8066cc','#7366cc','#6666cc']

Nobinobi
['#80ffea','#8aff80','#ffca80','#ff80bf','#9580ff','#ff9580','#ffff80']


// Apollo Styles
Throwback Rainbow
['#af2e26','#b1560f','#967727','#2d6f4c','#1f67b0','#224687','#643b95']

Combustion
['#bc0c0c','#9c0c0d','#a1350f','#bc620d','#b07d14','#a6930e','#99a010']

Ocean
['#025395','#0675c4','#178db1','#0474cc','#3878aa','#0c5a9a','#426da3']

Forest
['#274f35','#55713c','#318f29','#739959','#8e902c','#549e52','#6e6f32']

Nuit
['#2c3038','#34383f','#313337','#414549','#51555c','#65676e','#7a7e85']

Blep
['#ae483c','#3f6aa3','#6e5fa0','#ae8944','#2b8051','#b5670f','#9f2025']
```

**Comment by RheingoldRiver** [comment]
I think this is done, closing
