### ISSUE TITLE
Post sorting doesn't work

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#115]
Post sorting (New, Hot, Top (day) etc.) doesn't change no matter what option is selected

![IMG_5448](https://github.com/hariettem/Artemis/assets/77108475/d0802e45-1546-4453-9aa7-c24e13796e6b)
===
===
===
===
===
===
![IMG_5449](https://github.com/hariettem/Artemis/assets/77108475/94a0e334-3c20-40dd-8894-70e998f6232a)
===
===
===
===
===
===
![IMG_5450](https://github.com/hariettem/Artemis/assets/77108475/eb37f485-46ae-4250-a295-bf867a922894)

Artemis 0.1.2 iOS 16.5.1 iPhone 13 Pro

**Comment by hariettem** [comment]
fixed
