### ISSUE TITLE
Swiping with right thumb to go back periodically doesn’t work.

### ISSUE THREAD

**Issue by thesoloist-1** [hariettem/Artemis#116]
**Describe the bug**
As many people use their phones with one hand and those with large hands, the issue could be a problem but likely an easy fix. When holding the phone in your right hand and browsing in the comment section, when trying to swipe the edge of the screen to go back it sometimes does not work. Possibly due to the registration size being too small? The right thumb is usually flat when swiping where the left thumb uses the tip. Maybe slightly increasing the area of touch registration would fix this. 

**To Reproduce**
1. Click on any post with comments
2. Swipe with your right thumb
3. Scroll through the comments and try to swipe multiple areas of the left edge.

**Expected behavior**
Swipe back with no issues.

**Smartphone:**
 - Device: [iPhone12 Pro]
 - OS: [iOS 17 beta]
 - Version [alpha 0.1.2]

**Comment by lvndr-dev** [comment]
+1, and should be part of an extended UX deep dive.

**Comment by hariettem** [comment]
left edge area was expanded to 1/2 of screen to fix this
