### ISSUE TITLE
Two options to toggle avatars

### ISSUE THREAD

**Issue by zero-yeliad** [hariettem/Artemis#117]
**Describe the bug**
The settings menu has two areas to toggle the "Show Avatars" feature.

**To Reproduce**
Where to find:
1. Go to settings
2. Under "Appearance", "Show Avatars"
3. Under "Posts", "Show Avatars"

**Expected behavior**
One option.

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/5020168/0d189d60-b209-4d9b-b2c6-7e853d501db7)

**Comment by hariettem** [comment]
just fixed for next update thanks!
