### ISSUE TITLE
Tall image can't be closed.

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#120]
**Describe the bug**
Massively long images will not close. See video. I opened the image from the main feed, but opening it from the post also has the issue. 

**To Reproduce**
See https://kbin.social/m/liftoff@lemmy.world/t/119325/shared-on-Artemis and open image. Try and close it. 

**Expected behavior**
Image closes once swiped away from. 

**Screenshots**

https://github.com/hariettem/Artemis/assets/83763643/c642ea62-63e8-40d1-b8a0-9ab03ac2929e

**Smartphone (please complete the following information):**
iPhone Xs Max latest iOS.

**Comment by hiimmike** [comment]
I can 2nd this problem, video : https://imgur.com/a/bX41Gua

I tried zooming in and out.  I tried taping in all the translucent space around the image.  As well as swiping in all 4 directions.
