### ISSUE TITLE
Tall image does not scale/crop

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#121]
**Describe the bug**
See #120 . 

Tall image is displayed, but its full height is used for scaling rather than screen height. 

I need to scroll all the way down to get to the comments. 

**To Reproduce**
1. Go to https://kbin.social/m/liftoff@lemmy.world/t/119325/shared-on-Artemis
2. Scroll. 
3. Scroll way longer. All the way. 

**Expected behavior**
I know the blue arrow is there to go to first comment. I don't want to *click that to see the first comment* when I open the post - I want to see the first comment without extra steps. If I want to zoom in on the image I can click that whenever I want - if it doesn't lock down the overlay because it's too tall. 

**Screenshots**

https://github.com/hariettem/Artemis/assets/83763643/def728b5-5505-4f46-a463-c84d1782e1b4

**Smartphone (please complete the following information):**
iPhone Xs Max latest iOS 

**Additional context**

**Comment by hariettem** [comment]
fixed
