### ISSUE TITLE
Posts are doubling after pulling up to load more

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#122]
Whether on Home or All, posts double after you reach the bottom of the feed and pull up to load additional posts. Happens right after the break, it's the very last 1 or 2 posts before the break that are loaded again, with updated vote / boost / comment count.

**Comment by pvmzqahgyd** [comment]
<img width="448" alt="a" src="https://github.com/hariettem/Artemis/assets/77108475/509480b3-ea88-46ac-815a-184652216c5b">

**Comment by pvmzqahgyd** [comment]
<img width="448" alt="b" src="https://github.com/hariettem/Artemis/assets/77108475/d4a1f721-368c-4e00-9687-35b720dda21f">

**Comment by kruggiero97** [comment]
Not sure if there's a technical issue with this, but maybe it's related to similar behavior shown on kbin. I've noticed from the kbin website if I'm browsing then go to page 2, some of the posts on the bottom of page 1 are now at the top of page 2.

**Comment by lvndr-dev** [comment]
![image](https://github.com/hariettem/Artemis/assets/83763643/27a5d491-0055-4558-aba2-77d6f3162564)

I was scrolling slowly, and it seems I got the same issue.

**Comment by hariettem** [comment]
does this still repro in 0.1.7?

**Comment by hariettem** [comment]
if so, pls reopen
