### ISSUE TITLE
The back button always shows `Home` when navigating to comments from /m/All

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#124]
**Describe the bug**
When you navigate to a post (comment section) from All, the back button shows `Home`

**To Reproduce**
1. Go to All
2. Click on any post to view the comments. 3. See error

**Expected behavior**
If navigating to a comment section from All, show `All` on the back button and not `Home`.

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/49291963/f1bec5bb-63e3-4bf5-b030-057148a3634d)
![image](https://github.com/hariettem/Artemis/assets/49291963/fc7136e4-dc21-47e7-b9bd-82612ae1fd21)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.2/`eaa2a653-79df-4743-bac1-46239bae31f4`

**Comment by hariettem** [comment]
fixed
