### ISSUE TITLE
Brand New accounts load with a blank feed

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#125]
**Describe the bug**
If you have a brand new account without any magazine subscriptions nothing will show up on the home feed and doesn't seem to allow you to access /all. 

**To Reproduce**
1. Create and login with a fresh account
2. Click on the home feed
3. Search for a magazine 

**Expected behavior**
If an account is used without any magazine subscriptions I would expect the home feed to at least display the hot topics in /all.

**Screenshots**
https://github.com/hariettem/Artemis/assets/138167591/8ec8309d-d6a6-40bd-adec-fd8a65c2bf2d

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16
 - Version 0.1.2
Update: 4d6a8de5-b793-4507-922c-c3e6cb542842

**Additional context**

If you have any magazine subscriptions the Home Screen will show content from those and will allow you to select /all.

**Comment by Pankakke** [comment]
Logging into an account that had subscriptions and then logging back into the fresh account allowed me to see the "find magazine with.." option instead of just hanging on the search as seen in the above video.

https://github.com/hariettem/Artemis/assets/138167591/deef2e5d-12e7-444c-ade0-d8f0138795cb

But in order to see the list of subscription and the option to see /all you have to force close the app.

**Comment by hariettem** [comment]
added empty state suggesting user to sub
