### ISSUE TITLE
Account Switcher doesn't work if usernames are the same at each instance

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#126]
**Describe the bug**
I have two accounts, Pankakke at Kbin.social and Pankakke at Kbin.cafe. If I log into one I will see the add user button in the corner, if I click that and log into the other I will see the add user button instead the ability to switch to the other account, 

**To Reproduce**
1. Have two accounts with the same username on two different instances 
2. Login to one account 
3. Click add user and login to the other account
4. See the add user button remain

**Expected behavior**
I would expect to be able to switch between both accounts as they belong to different instances and are not the same.

**Screenshots**
https://github.com/hariettem/Artemis/assets/138167591/85ebfd34-a5bf-431d-bf97-a219c59d3e8b

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16
 - Version 0.1.2
Update: 4d6a8de5-b793-4507-922c-c3e6cb542842

**Comment by hariettem** [comment]
fixed
