### ISSUE TITLE
Ability to swipe up/down to bring the reply window up/down

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#128]
**Is your feature request related to a problem? Please describe.**
Currently if you try to drag the reply window down the window will just bounce right up. The only way currently to bring the window down is to tap on the top of it and then tap on the text field to bring it back up with the keyboard. 

**Describe the solution you'd like**
I would love to see the ability to drag or flick down from the top of the window down in order to bring the window down. Then be able to drag or flick up on the window to have it move back up and have the keyboard up.

**Additional context**
Video of the window bouncing back up when you try and drag it from the top down. 

https://github.com/hariettem/Artemis/assets/138167591/a1641d4f-d22d-4c1b-b53b-cd440174b9b0

**Comment by hariettem** [comment]
impl
