### ISSUE TITLE
Url in post doubled at bottom

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#129]
**Describe the bug**
When a url appears multiple times in a post it will show up twice at the bottom url summary. 

**To Reproduce**
1. Create post
2. Post same url in post twice. 
3. Post. 

**Expected behavior**
Url duplicate is filtered out. (Also, unicode is not parsed in url preview)
**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/83763643/b5454fa6-15f4-485a-a78f-99f42fe2d3da)
**Smartphone (please complete the following information):**
iPhone Xs Max, ios 16.5.1

**Additional context**

**Comment by hariettem** [comment]
fixed/// ?
