### ISSUE TITLE
Upvote/boost button not selectable in community view

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#13]
**Is your feature request related to a problem? Please describe.**
Attempting to tap boost or upvote within community view (and comments) has the same behavior as tapping said post or comment. As in, when you tap upvote in community view, you are taken to the comment section of the post. If you tap upvote on a comment, the comment is collapsed.

**Describe the solution you'd like**
Allow the ability to upvote, boost, and reply from the icons presented.

**Additional context**
![19F9EC70-C560-4113-8E20-D9C36D3CA9B2_1_201_a](https://github.com/hariettem/Artemis/assets/49291963/7728b184-6cec-4596-a418-1b7133019b4c)
![C1158011-47CC-4769-8083-E317677B0957_1_201_a](https://github.com/hariettem/Artemis/assets/49291963/7483c82d-f985-4765-b1a4-9f03fabe1d75)

**Comment by hariettem** [comment]
ahhh the ol days :P
