### ISSUE TITLE
Embedded images not showing in app

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#130]
[This post](https://kbin.social/m/RedditMigration/t/122238/My-Reddit-GDPR-Request-took-20-days-this-is-what) has an embedded image and is recognized as such in Artemis, however, no image is actually shows when the post is opened in the app. Works normally in the kbin web app.

**Comment by pvmzqahgyd** [comment]
![1](https://github.com/hariettem/Artemis/assets/77108475/876a52a7-022d-4d15-a49f-ba711536093b)

**Comment by pvmzqahgyd** [comment]
![2](https://github.com/hariettem/Artemis/assets/77108475/23312fcc-f759-4d7d-a25a-e4db7dc4fe5d)

**Comment by pvmzqahgyd** [comment]
![3](https://github.com/hariettem/Artemis/assets/77108475/3623d1f6-3bb2-4ffe-b57e-f88665d11030)

**Comment by pvmzqahgyd** [comment]
![4](https://github.com/hariettem/Artemis/assets/77108475/f4f8a8a9-f827-4ca4-915f-2fb8ca6b8e49)

**Comment by thesoloist-1** [comment]
+1 same issue on my end. 

https://github.com/hariettem/Artemis/assets/97246028/a3f8d7af-e6d0-4f8b-a406-f6f9465bbe51

**Comment by Uprise42** [comment]
![image](https://github.com/hariettem/Artemis/assets/58179605/bde70cba-be9d-433a-b966-c37d70989396)

![image](https://github.com/hariettem/Artemis/assets/58179605/0e4fe073-a7da-4212-a07e-2ef67031b9f7)

Happening on iOS17

Version: 0.1.7

Update: 2307.14.01.38
(d0da81fb-0934-43ff-b8d0-facfb6c61c5e)}

Channel: preview

**Comment by hariettem** [comment]
fixed
