### ISSUE TITLE
Duplicated "Subscribe to magazine" button when browsing All

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#131]
**Describe the bug**
While browsing All, after going to a comments page then going back to all I noticed a doubled up "Subscribe to magazine" button. This doesn't happen 100% of the time, though. 

**To Reproduce**
1. Go to All
2. Click on a post to see the comments
3. Click back in the top left or swipe to go back

**Expected behavior**
Perhaps there shouldn't even be a button on All to subscribe to the magazine, since  you can't really subscribe to All anyway. 

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/49291963/8f089fc2-4d31-4ad7-afcc-ce7b88d9c8b9)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.2/`75b87e95-1606-4b61-b07d-c73be99fb871`

**Additional context**
You might have to navigate to multiple different comment sections and go back to All to reproduce.

**Comment by lvndr-dev** [comment]
+1, same issue. IIRC we will find a better solution for the subscribe button.

**Comment by hariettem** [comment]
fixed, shouldnt show on all
