### ISSUE TITLE
Prefetching posts shows dated duplicates

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#133]
**Describe the bug**
Next page scroll prefetched the same post from hours ago. 

**To Reproduce**
Scroll down, and if done fast enough posts repeat with old data. 

**Expected behavior**
Before prefetching the recently displayed url/id is known, so duplicates should not happen. 

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/83763643/a9af63cb-f51c-4ec3-86ad-5c61e16b23ba)
**Smartphone (please complete the following information):**
 iPhone xs max

Version 0.1.2
Update: f291702c-302f-4ad7-91c7-dd49c865675b

**Additional context**

**Comment by lvndr-dev** [comment]
![image](https://github.com/hariettem/Artemis/assets/83763643/ac97c169-dd09-40c8-bb17-0548ad5e22b4)

Apparently also happening without prefetch? Note thick space of separator.

**Comment by hariettem** [comment]
This is due to a feed changing as votes and time goes on. You can see it happen when paging on the website. I have a todo to check for and remove existing posts when loading next page.

**Comment by hariettem** [comment]
Tho ur first issue, could just be from duplicate communities in different instances? Can u check the instance of it (planet).

**Comment by lvndr-dev** [comment]
> Tho ur first issue, could just be from duplicate communities in different instances? Can u check the instance of it (planet).

I checked before and should have mentioned - they were the same instance. 

![image](https://github.com/hariettem/Artemis/assets/83763643/e31a7c4f-7bc9-4684-b35c-5097a52f8e88)
![image](https://github.com/hariettem/Artemis/assets/83763643/3250166b-8e4c-4a5f-bcde-6f77e43665aa)

**Comment by hariettem** [comment]
Can you go on each and share the link for both here? And also, see if either loads something completely different.

the server doesn’t cache (it actually gets killed), so it shouldn’t have a post with the state from hours ago.

**Comment by lvndr-dev** [comment]
![image](https://github.com/hariettem/Artemis/assets/83763643/aba9c7b8-9df2-439a-9a4a-e9a6ace8db5d)

Never mind. I am an idiot, and so is that user because he posted the exact same thing twice and didn't notice. 

Had to leave Artemis to see this, though.
