### ISSUE TITLE
Settings page crashing

### ISSUE THREAD

**Issue by thelazurus** [hariettem/Artemis#134]
**Describe the bug**
When trying to access the settings page, the app crashes.

**To Reproduce**
1. Open the app
2. Click on settings
3. App crashes

**Expected behavior**
The settings page, or an under construction page.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.6 Public Beta 4
 - Version: latest version on expo, I can't check the version number since I can't access settings

**Comment by thelazurus** [comment]
https://github.com/hariettem/Artemis/assets/9217220/076659e2-f61f-4f0c-bbc2-2634e14c7155

**Comment by Prouvaire** [comment]
For me, this bug manifested only the first time the program is run after installation. Opening the app subsequent times after the initial crash no longer produces the crash.

Devices tested on (crashed both devices after clicking on Settings immediately after installing the apk):
- LG V60, Android version 13
- Huawei Mediapad M5, Android version 9

Artemis app version:
- Preview channel
- Update: 9eb87639-5539-4195-98eb-2c1e6210f82d

**Comment by IcerOut** [comment]
Alright, I've tested it a bit by reinstalling the app  over and over

Seems even after the patch, it still occurs. It's only the first time after installing the app, afterwards it always works. 
And after installing, if you close the app and reopen it, the settings page works straight away and you don't get the crash.

- S23 Ultra, Update 9eb87639-5539-4195-98eb-2c1e6210f82d

**Comment by SARankDirector-Minecraft** [comment]
I had the same issue. I'm on iOS 16.1, iPhone 13 Pro. Sideloaded w/ sideloadly

**Comment by hariettem** [comment]
fixed on 0.1.7
