### ISSUE TITLE
While backing out of a comment section the screen turned partially white and froze. I had to close out the app to get back in

### ISSUE THREAD

**Issue by slicedcheesegremlin** [hariettem/Artemis#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. alpha.1]

**Additional context**

**Comment by hariettem** [comment]
any repro on 0.1.7?

**Comment by slicedcheesegremlin** [comment]
it seems fine now, thanks
________________________________
