### ISSUE TITLE
Reply issue: Parent no scroll

### ISSUE THREAD

**Issue by AndyProk** [hariettem/Artemis#139]
**Describe the bug**
When replying to a comment, the comment you're replying to appears above the text field for inputting your reply, but it doesn't seem to be able to scroll, which cuts off everything but the beginning of long comments.

**To Reproduce**
1. Look for a long comment
2. Open the reply interaction
3. Try scrolling the review display of the comment you're replying to 

**Expected behavior**
Being able to see the entire comment I'm replying to, not just the start.

**Screenshots**
![Screenshot_20230703-064544](https://github.com/hariettem/Artemis/assets/1254316/3584698b-56db-41aa-ac25-5485f52e5d3a)

**Smartphone (please complete the following information):**
 - Device: Nokia G60 5G
 - OS: Android 13 (not rooted or otherwise modified)

**Comment by hariettem** [comment]
fixed with 0.1.7
