### ISSUE TITLE
App version not shown in settings tab on 0.1.5

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#140]
**Describe the bug**
The app version is not displayed in the settings tab.

**To Reproduce**
1. Go to the settings tab
2. See error

**Expected behavior**
To be able to see the app version for bug reports.

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/49291963/54eec653-20ad-4e08-adaa-ddedc20a0649)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: IOS 16.5.1
 - Version 0.1.5

**Comment by Alaric323** [comment]
Can confirm, same as the above screenshot on Android.

**Comment by SARankDirector-Minecraft** [comment]
Fixed on iOS at least

**Comment by IcerOut** [comment]
It's fixed on Android as well

**Comment by Alaric323** [comment]
Can confirm Android fixed too.
