### ISSUE TITLE
Status bar not visible

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#15]
**Describe the bug**
Status bar is not visible while using the app

**To Reproduce**
1. Open Artemis
2. See error

**Expected behavior**
Status bar is visible while using the app

**Screenshots**
![Screenshot_20230624-105551.png](https://github.com/hariettem/Artemis/assets/11584387/ed032461-1409-4972-b7ed-8e322437b3a9)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 9 Pie
 - Version: alpha.1

**Additional context**
Untested with dark mode for now.

**Comment by RheingoldRiver** [comment]
Can confirm this for a Samsung android device in dark mode, see:
![image](https://github.com/hariettem/Artemis/assets/18037011/3eef3b1c-03b3-45fe-acff-e6ba8601c5dc)
