### ISSUE TITLE
Add support for "active" sorting

### ISSUE THREAD

**Issue by evanfoster** [hariettem/Artemis#152]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I've come to really enjoy the "active" sort available on kbin's desktop and mobile sites. It would be awesome to be able to use that same sort in Artemis for all magazines, as well as my subscriptions.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by RheingoldRiver** [comment]
this seems done!
