### ISSUE TITLE
Viewing an image in landscape reverts it back to portrait

### ISSUE THREAD

**Issue by thesoloist-1** [hariettem/Artemis#161]
**Describe the bug**
When browsing in landscape mode, when you click to view an image it rotates back to portrait mode. Same thing occurs when viewing a post’s picture in landscape mode. However when this happens in the post section the app can become quite unresponsive and needs a restart. 

**To Reproduce**
1. Browse in landscape
2. Click on an image to view it
3. App reverts to portrait

**Expected behavior**
Should stay in landscape mode.

**Screen recording**
https://github.com/hariettem/Artemis/assets/97246028/2f89970d-d48c-4d4a-a2db-0f9fad64243d

**Smartphone:**
 - Device: iPhone 12 Pro
 - OS: iOS 17 beta
 - Version: Version 0.1.5
Update: 748e5d95-4fce-4adb-a2b7-df805af04bf9

**Comment by evanfoster** [comment]
Can't seem to repro this on Android, might be an iOS-only bug.
