### ISSUE TITLE
Artemis does not always update edited posts

### ISSUE THREAD

**Issue by SARankDirector-Minecraft** [hariettem/Artemis#163]
**Describe the bug**
When a post is edited, that post will not always be updated to reflect those edits in Artemis on a reload

**Expected behavior**
Artemis would update edited posts on reload

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.1
 - Version 0.1.5

**Comment by hariettem** [comment]
does this repro with 0.1.7 when you pull to refresh?

**Comment by SARankDirector-Minecraft** [comment]
Can confirm, issue appears to have resolved. Closing the report
