### ISSUE TITLE
Closing post quick actions opens the post instead

### ISSUE THREAD

**Issue by ZeroZeroOne-dev** [hariettem/Artemis#167]
**Describe the bug**
When trying to close a post's quick actions by swiping in the opposite direction you get send to the post itself most of the time.
Unless you are *very* precise where you place your finger (the little white space under the thumbnail)

![image](https://github.com/hariettem/Artemis/assets/254635/ea047ddb-13e4-44fb-a299-c29a8c773268)

**To Reproduce**
1. Go to the home page
2. Swipe from left to right on a post to open the quick actions
3. Swipe from right to left on a post to close the quick actions
4. Instead you get redirected to the post

**Expected behavior**
Closing the quick actions

**Screenshots**
Video: https://github.com/hariettem/Artemis/assets/254635/e6a469a9-f882-4998-985a-8e298438a90d

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.5

**Additional context**
A good example for quick actions is the mail app

**Comment by RheingoldRiver** [comment]
Currently, we can't repro this. If you still can, then feel free to reopen 👍
