### ISSUE TITLE
Text posts not loading when visiting a specific magazine via subscribed magazines list

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#171]
This is an odd one but I'll try to explain as best as I can. Opening any post from Home or All works ok. 
However, when opening a magazine from your subscriptions, text (aka self) posts would not load.
It only happens when the magazine is visited via the subscribed magazines list, and only text posts fail to load.

App version 0.1.5 Update 2307.04.00.03 Channel: preview
iOS 16.5.1
iPhone 13 mini

**Comment by pvmzqahgyd** [comment]
https://github.com/hariettem/Artemis/assets/77108475/14bdabc0-d18b-4be1-8d89-1cd29ef7db9d

**Comment by hariettem** [comment]
does this still repro on 0.1.7?

**Comment by Pankakke** [comment]
> does this still repro on 0.1.7?

0.1.7 seems to have solved this issue 🎉

**Comment by pvmzqahgyd** [comment]
No issues for me on 0.1.7 / 2307.11.01.55 😀
