### ISSUE TITLE
Add white theme color

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#172]
Please consider eventually adding a white theme color (Snow? Yuki?) with #F2F3F4 or similar color for breakpoints etc.

**Comment by pvmzqahgyd** [comment]
<img width="472" alt="Screenshot 2023-07-04 at 7 26 15 AM" src="https://github.com/hariettem/Artemis/assets/77108475/dcd867f6-fcc8-438c-bd6d-3954cb6f222b">

**Comment by hariettem** [comment]
@lvndr-dev ? 👀

**Comment by lvndr-dev** [comment]
> @lvndr-dev ? 👀

Definitely, though we need to settle on how we handle color schemes. While Google's MD3 is a nice catch all solution, I personally am not a fan of letting the design be led by Google's idea of color theory. If the devs could provide a theming solution outside of the MD3 adaptive colors I'll be able to create far better color schemes tailored to use case and taste.
