### ISSUE TITLE
Save photo to album doesn't save the photo

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#174]
**Describe the bug**
When you try to save a photo to album by holding the photo with your finger and tapping "save to the album", if the photo is saving somewhere, I am not sure where.

**To Reproduce**
1. Go to a photo in the app
2. Hold the photo with your finger
3. Tap "save to the album"

**Expected behavior**
The photo to show up in recents of my photo album.

**Screenshots**
https://github.com/hariettem/Artemis/assets/49291963/2f997e73-c224-46e5-a6b5-792a4df7b226

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.5/Update: 2307.04.00.03
(7c9f59c4-801f-4a6f-b140-07d3635c39f6)

**Comment by SARankDirector-Minecraft** [comment]
Also having this issue on iPhone 13 pro, iOS 16.1
