### ISSUE TITLE
Nothing loads when no magazines are subbed

### ISSUE THREAD

**Issue by Uprise42** [hariettem/Artemis#175]
**Describe the bug**
Home Screen is completely empty when using a new account

**To Reproduce**
1. Create an account on the website
2. Log into new account in artemis
3. Go to Posts feed

**Expected behavior**
An expected behavior is to load a default “all” feed

**Screenshots**
I forgot to grab them. Sorry. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - OS: iOS 17
 - Version Version: 0.1.5

Update: 2307.04.00.03
(7c9f59c4-801f-4a6f-b140-07d3635c39f6)}

Channel: preview

**Additional context**
Nothing else to add

**Comment by hariettem** [comment]
fixed
