### ISSUE TITLE
Gray out read posts

### ISSUE THREAD

**Issue by Uprise42** [hariettem/Artemis#176]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When on Apollo, after reading a post it would Darken the text to show you’ve read that post. This could be helpful for when a link is posted to multiple subs, you can tell if that is the case vs just seeing the same post repeatedly. 

**Describe alternatives you've considered**
Any visual indicator that a post has been read is helpful

**Comment by SARankDirector-Minecraft** [comment]
This would be very useful

**Comment by hariettem** [comment]
added
