### ISSUE TITLE
upvotes continue to add up on Artemis client side after error message

### ISSUE THREAD

**Issue by iNeedScissors67** [hariettem/Artemis#177]
**Describe the bug**

 I'll upvote a comment by hitting the up arrow next to the user name, it'll register it and then I'll get an orange popup stating there was a problem upvoting. Then I can go upvote that comment again, and they'll keep adding up as long as the orange popup happens. Just voted a comment from +13 to +18 to test it. It sits at +15 on kbin.social website and I can keep adding it up continually on Artemis.

**To Reproduce**
1. Go to a comment
2. Click on upvote arrow next to username on a comment.
4. See error code in orange popup at top of screen.
5. Repeat as long as error code message persists

**Expected behavior**
An upvote on one tap, removal of upvote on second tap

**Screenshots**

![Screenshot_20230704-131841_Artemis](https://github.com/hariettem/Artemis/assets/138617122/282cec4a-9ec1-4b56-94ba-113bfbc5a43f)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: most recent official
 - Version most recent official

**Comment by stephen304** [comment]
Also noticed this, tldr the app just needs to undo the upvote increment if an error occurred.

**Comment by hiimmike** [comment]
I’m getting this error constantly, near 100% of the time. Happens when voting on posts and comments - up and down voting. 

App version 0.2.0, iPhone XS, iOS 16.6.

I have tried deleting the app and reinstalling.  Does not help.

**Comment by hariettem** [comment]
@hiimmike oh thats weird, upvoting and downvoting should work 99% of the times now with API. Haven't seen this anymore. Does it work on web?

**Comment by hiimmike** [comment]
@hariettem 
I’m embarrassed…  but as they say - the problem was between the chair and the phone.  

All set now  :)
