### ISSUE TITLE
Swipe gesture on posts stuck

### ISSUE THREAD

**Issue by thesoloist-1** [hariettem/Artemis#178]
**Describe the bug**
Swipe gesture to show votes seems to get stuck and won’t return to normal state until restart.

**To Reproduce**
1. Go to threads list
2. Swipe on a post to vote

**Expected behavior**
Should return to normal state when swiping back.

**Screenshots**
https://github.com/hariettem/Artemis/assets/97246028/bfa9f7d2-b1a4-4e4f-8be6-b8b71427d807

**Smartphone:**
 - Device: iPhone 12 Pro
 - OS: iOS 17 beta
 - Version: Version: 0.1.5

Update: 2307.04.16.58
(e8c32a4d-b997-46ca-af77-d9574194509b)}

**Comment by geneccx** [comment]
You can swipe it back by starting from the upvote button but I agree, I think when navigating to a different page it should return them to default state.

The same issue exists for the sort order button in the top right:

https://github.com/hariettem/Artemis/assets/1152573/4157efe2-44fe-4174-b93d-ba57a8dbaec2

**Comment by thesoloist-1** [comment]
Yup you are correct swiping the votes part returns it to normal state. However being able to swipe anywhere on the post would be efficient. I do know Hariette is working on the swipe gesture interactions, so will likely be adjusted in the future
