### ISSUE TITLE
Support for following domains

### ISSUE THREAD

**Issue by geneccx** [hariettem/Artemis#179]
kbin has a hidden feature that allows a user to follow any domain.

For Fediverse domains, this lets you see, and follow all communities at once:
https://kbin.social/d/lemmy.worlds
https://kbin.social/d/mastodon.social

This also works for viewing all content related to a domain in kbin:

https://kbin.social/d/imgur.com
https://kbin.social/d/twitter.com

The list of subscribed domains for the current user can be managed here: https://kbin.social/settings/subscriptions/domains

**Describe the solution you'd like**
A way to manage subscriptions and view these by domain, similar to magazines.

**Additional context**
For more details and examples, check out https://kbin.social/m/kbinMeta/t/135413

**Comment by hariettem** [comment]
added!
