### ISSUE TITLE
Add Ability to Subscribe to Communities

### ISSUE THREAD

**Issue by NonITExpert** [hariettem/Artemis#182]
The function to search for communities is working well. Now we need a way to see community datails, and then to subscribe to it.

**Comment by kruggiero97** [comment]
A sidebar is in the works, also when you are on a communities feed, you should be able to hit the `+` in the top right corner to subscribe to said community.

**Comment by NonITExpert** [comment]
That's just it:  I don't see a "+" sign anywhere when I access a new community in the android Artemis app. Nor do I see a minus sign when I access a community I've subscribed to. What am I missing?  If you could please show me a with a screenshot what I'm supposed to be seeing it'd help.

https://github.com/hariettem/Artemis/assets/138516886/afc371f2-606e-4b5f-8080-3246781f9f54

**Comment by kruggiero97** [comment]
> That's just it:  I don't see a "+" sign anywhere when I access a new community in the android Artemis app. Nor do I see a minus sign when I access a community I've subscribed to. What am I missing?  If you could please show me with a screenshot what I'm supposed to be seeing it'd help.

![image](https://github.com/hariettem/Artemis/assets/49291963/bedfc7da-1852-432a-95b4-05416c466c5b)

Which version of the app do you show under `Settings`

**Comment by NonITExpert** [comment]
android version 2307.04.16.38

**Comment by pvmzqahgyd** [comment]
It's gone for me too on iOS using the current TestFlight version.

**Comment by SARankDirector-Minecraft** [comment]
The icon is also missing for me on the latest Verision: 2307.04.00.03 had it but version 2307.04.16.58 does not

I’m on iOS 16.1, iPhone 13 Pro

**Comment by NonITExpert** [comment]
I just updated to android 2307.04.16.58, and can confirm icon is not there.

**Comment by hariettem** [comment]
subscribing is in the sidebar and the "Menu" in top bar
