### ISSUE TITLE
Feed disappears as it fetches more posts

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#183]
**Describe the bug**
While scrolling the feed for a while I have encountered a bug that causes the feed to disappear during a refresh while it fetches more posts. It does eventually come back and show the feed populated with more posts but sometimes you end up hanging on a blank feed for a bit. 

**To Reproduce**
1. Scroll the home feed like crazy, keep scrolling and scrolling. 
2. The feed should eventually disappear and show nothing while it fetches more posts. 

**Expected behavior**
I would expect to still see previous posts on the screen while the app fetches more posts. 

**Screenshots**
https://github.com/hariettem/Artemis/assets/138167591/0d0c2457-fc59-4246-946e-7572607499eb

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16.5.1
 - Version Version: 0.1.5
Update: 2307.04.16.58
(e8c32a4d-b997-46ca-af77-d9574194509b)}

Channel: preview

**Comment by SARankDirector-Minecraft** [comment]
Related to #158?

**Comment by hariettem** [comment]
does this repro on 0.1.7?

**Comment by Pankakke** [comment]
> does this repro on 0.1.7?

Haven't been able to replicate it while scrolling down. If you scroll up on the page really fast after scrolling for a while you will see a blank feed eventually but it does populate now much quicker.

**Comment by hariettem** [comment]
improved w update today
