### ISSUE TITLE
Add Option to Save Posts/Comments

### ISSUE THREAD

**Issue by NonITExpert** [hariettem/Artemis#185]
I don't know in what dev stage this is planned, but wanted to get this submitted now nonetheless. Please add option to save post/comment like Reddit apps. This is different from share where I believe content can be saved on your device. Instead, "Save" keeps the content in your account.

**Comment by NonITExpert** [comment]
Adding an example from a Lemmy app that shows the icon for the save (to your profile/account) function.
![Screenshot_20230705_183754_Jerboa](https://github.com/hariettem/Artemis/assets/138516886/5574c53f-7597-4d1a-b11b-500ef82b86b6)

**Comment by NonITExpert** [comment]
Same as issue 132.

**Comment by RheingoldRiver** [comment]
Closing as dupe of #132
