### ISSUE TITLE
kbin Downtime notice

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#186]
Kbin announced downtime.

![image](https://github.com/hariettem/Artemis/assets/83763643/d8cb32b6-29d5-4c3f-942a-0ec8ee93b1ae)

Once an API is established, I am certain such notices will be displayed better, and are able to be integrated into a notice for users of Artemis.

**Comment by RheingoldRiver** [comment]
hmm i am not counting on this any time soon from kbin, im going to close this
