### ISSUE TITLE
UI switches from light theme to dark theme

### ISSUE THREAD

**Issue by wkissam** [hariettem/Artemis#188]
**Describe the bug**
When selecting magazine the UI from light to dark theme
**To Reproduce**

Currently on light theme and when I tap "home" the UI turns black theme, the list looks fine but black background instead of white. 

**Expected behavior**
I would expect the ui to keep the selected theme

**Screenshots**
**Smartphone (please complete the following information):**
 - Device: [iPad Pro 2021, iPhone 8]
 - OS: [iPadOS 17, iOS 16.5]
 - Version [Version: 0.1.5

Update: 2307.04.16.58
(e8c32a4d-b997-46ca-af77-d9574194509b)}

Channel: preview]

**Additional context**
The reverse of this problem does not occur when using a dark theme.

**Comment by hariettem** [comment]
does this still repro on 0.1.7?

**Comment by wkissam** [comment]
Yes it still doing it. Tested on both devices again.

**Comment by RheingoldRiver** [comment]
hey @wkissam sorry to ask once again, but is it still happening on 0.2.0? (going through open tickets again)

**Comment by wkissam** [comment]
@RheingoldRiver it is working properly now!
