### ISSUE TITLE
Ability to see exact time for post/comment

### ISSUE THREAD

**Issue by IcerOut** [hariettem/Artemis#189]
**Is your feature request related to a problem? Please describe.**
Currently all dates/times in the app are relative (3m ago, 9h ago, etc.). There's no way to see the exact date and time when sometime was posted (to compare 2 comments, for example, and see which was posted first. If both were posted close to the same time they'd just both say "9h ago" for example)

**Describe the solution you'd like**
Clicking or holding on a time label should show a tooltip containing the exact date (in the phone's preferred date and time format). It could automatically fade away after a few seconds (or when you click somewhere else)
Being able to copy it as well would be nice, but way less important IMO.

**Describe alternatives you've considered**
Checking the post/comment time in the webUI (not the PWA, it has the same issue)

**Additional context**
N/A

**Comment by Alaric323** [comment]
I would say this doesnt need to be an "always on thing"?  Tapping the time to make it toggle seems like a good method of implementation.

**Comment by hariettem** [comment]
added a tooltip on an update scheduled for tomorrow :)
