### ISSUE TITLE
Magazine doesn't appear with direct search

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#191]
**Describe the bug**
I was trying to search for the magazine entertainment@beehaw.org. So I typed in the search "entertainment" to which no results would come up. It's not until you search "movies" that entertainment@beehaw.org will appear in the search results. 

**To Reproduce**
1. Go to search and search for "entertainment"
2. You should see no results found.
3. Then search for "movies"
4. You should then see entertainment@beehaw.org in the results

**Expected behavior**
I would expect that directly searching for a magazine by its title should have it appear in the search results.

**Screenshots**
https://github.com/hariettem/Artemis/assets/138167591/e714e833-04ab-485f-94cb-fabc7557ecc8

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.5

Update: 2307.05.04.19
(199cfa44-89d0-45fb-885c-b0f9009a2f70)}

Channel: preview

**Comment by IcerOut** [comment]
Doesn't happen for me, entertainment@beehaw.org shows up in the first search

S23 Ultra, Android 13, Channel preview, Version 0.1.5 Update 2307.05.04.19

**Comment by Pankakke** [comment]
You're correct! It seems to be working now. Might have had something to do with the beginnings of today's Kbin server updates. I'll keep an eye on it to see if it happens again.
