### ISSUE TITLE
More specific sort by button (the button to the right of Home)

### ISSUE THREAD

**Issue by Auxygen** [hariettem/Artemis#193]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Could there be a way for us to sort more specifically than just "Top (day)" (button to the right of Home), like Top Six Hours or similar? I'm finding older posts and that's the only fix to see new posts constantly. It's not an issue with the app since it's the same on each site, kbin, lemmy, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hariettem** [comment]
added!
