### ISSUE TITLE
Long text posts are overflowing the post space, making it unable to be read

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#197]
**Describe the bug**
It seems that text posts that are long can be too long and overflow the space dedicated to the text post.

**To Reproduce**
1. Go to a long text post
2. See error

**Expected behavior**
Show the whole text post in the dedicated space.

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/49291963/caae4f7a-7031-4fca-9d3d-b1d43349c7d4)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.5
Update: 2307.06.00.28
(026dd2c8-be71-406c-b27d-c537fc60b575)}

Channel: preview

**Comment by Uprise42** [comment]
Just posting another example, this is still occuring in the current version. 

Device: iPhone 14 Pro Max
OS: iOS 16.5.1

Version: 0.1.5

Update: 2307.06.00.28
(026dd2c8-be71-406c-b27d-c537fc60b575)}

Channel: preview

![image](https://github.com/hariettem/Artemis/assets/58179605/75f267ea-190a-460b-8ce4-fd33045ecdb9)

**Comment by Kraiden** [comment]
Still present in `2307.10.03.47`

See: @kbinMeta@kbin.social -> Sort by "Top, All"

[/kbin server update - or how the server didn't blow up](https://kbin.social/m/kbinMeta/t/68541/shared-on-Artemis)
[A small FAQ to hopefully help new users to kbin](https://kbin.social/m/kbinMeta/t/11493/shared-on-Artemis)

**Comment by NonITExpert** [comment]
Still present in 2307.10.16.09

**Comment by ex-youth** [comment]
example of it occurring with a list: 

![IMG_1783](https://github.com/hariettem/Artemis/assets/137928675/001aef93-4d1b-46f3-8dc8-9467e1a8ba03)


https://kbin.social/m/fediverse@lemmy.world/t/131427/shared-on-Artemis

**Comment by chris-y** [comment]
Example with an image:

https://fedia.io/m/retrogaming@lemmy.world/t/89399/Retrospective-Micronaut-One-ZX-Spectrum-1987

![Screenshot_20230710-220011.png](https://github.com/hariettem/Artemis/assets/1818803/3e0e41cf-dda9-418f-bd36-790d6e9bb6d8)

**Comment by Prouvaire** [comment]
Some more examples - see three attached screenshots.

Device: LG V60
OS: Android 13
Artemis version: 0.1.5 Update 2307.07.21.24


![Screenshot_20230711-120758](https://github.com/hariettem/Artemis/assets/138431362/9f9407ef-f918-4a22-8ba2-7d9720447d4b)
![Screenshot_20230711-122120](https://github.com/hariettem/Artemis/assets/138431362/55af75be-749f-4910-9b08-2d9ff0eb4c1c)
![Screenshot_20230711-122916](https://github.com/hariettem/Artemis/assets/138431362/41bd89c6-1314-45d2-b0c6-f92a3ae7dd56)

**Comment by SossyPants** [comment]
Same issue on Pixel 6 Pro, Android 13 

Version: 0.1.7

Update: 2307.11.01.55
(11363bd1-9b4f-42ef-b1b3-58aea8b72c25)}

![Screenshot_20230711-184855](https://github.com/hariettem/Artemis/assets/139263686/2310bbc0-0eb1-4e74-a312-4befc6410c61)
![Screenshot_20230711-184912](https://github.com/hariettem/Artemis/assets/139263686/e318d926-0fb3-4935-8d5c-421de5766ed6)

**Comment by win8linux** [comment]
Can be reproduced using the [Artemis FAQ](https://kbin.social/m/ArtemisApp/t/121025/):
![image](https://github.com/hariettem/Artemis/assets/11584387/e242985f-413d-4cae-8f8e-7ce2f311d6cb)

Device: iPhone 7 Plus
OS: iOS 15.7.6
Version: 0.1.7
Update: 2307.10.20.24
(1f4e0e09-4438-4a48-8851-04de0f4003f5)}
Channel: dogfood

**Comment by hariettem** [comment]
fixed!
