### ISSUE TITLE
Disabling haptics does not apply to settings toggles

### ISSUE THREAD

**Issue by SARankDirector-Minecraft** [hariettem/Artemis#198]
**Describe the bug**
Disabling haptics does not apply to settings toggles

**Expected behavior**
Disabling haptics should prevent haptic feedback when toggling switches in settings

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 16.1
 - Version: 0.1.5

**Comment by hariettem** [comment]
ah, those are built-in to system. let me see if there's a way to set that programmatically.

**Comment by SARankDirector-Minecraft** [comment]
Fair, however it's still better to  not have any haptics when disabling haptics

**Comment by stephfinitely** [comment]
Toggling haptics setting on version 0.2.0 on android 13 isn't effecting haptics at all.

**Comment by hariettem** [comment]
fixed!
