### ISSUE TITLE
Add option to adjust the font size

### ISSUE THREAD

**Issue by NonITExpert** [hariettem/Artemis#199]
Please add an option sooner rather than later to adjust the font size smaller or larger inside the app settings, so user doesn't have to change it universally across the device. Here's an example of how that could be set up:
![Screenshot_20230705_185139_Jerboa](https://github.com/hariettem/Artemis/assets/138516886/98c4e199-bdf6-4a51-b388-49153b224f3a)

**Comment by drewbs-b** [comment]
Would also appreciate this

**Comment by hariettem** [comment]
added
