### ISSUE TITLE
Magazine name overlapping with ‘sort-by’ icon.

### ISSUE THREAD

**Issue by hiimmike** [hariettem/Artemis#205]
**Describe the bug**
When viewing magazines with long names, the name displayed at the top of the screen overlaps with the ‘sort-by icon’.  

**To Reproduce**
1. Go to …  any magazine with a long name, e.g. damnthatsinteresting or homeimprovement.
2. Click on …  nothing, just few the magazine title at the top of the page.
3. Scroll down to …  no need to scroll, keep your eyes up too.

**Expected behavior**
Either a shortened magazine name, or seeing it cut off with some “…” appended to the end, or maybe smaller font so it fits?

**Screenshots**

https://imgur.com/a/C9KXJU1

https://imgur.com/a/H1F2uLh

https://imgur.com/a/8LW9sX2

**Smartphone (please complete the following information):**
 - Device: iPhone XS 
 - OS: 16.5.1
 - Version: 0.1.5

**Additional context**
Low priority issues.  I also looked thru GitHub and didn’t see this mentioned?  If it was I do apologize.

**Comment by pvmzqahgyd** [comment]
Related https://github.com/hariettem/Artemis/issues/181
