### ISSUE TITLE
Share direct link to comment

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#208]
**Is your feature request related to a problem? Please describe.**

Long pressing a comment now gives a menu for post interactions. There is no way to share the direct link. 

**Describe the solution you'd like**

A button to "Share link" and "Share Fediverse link" on long press. 

**Additional context**
![image](https://github.com/hariettem/Artemis/assets/83763643/d07ad6e4-1a09-4c9f-99d9-cdd31ad85b3c)

**Comment by RheingoldRiver** [comment]
https://artemis.camp/m/space@lemmy.world/t/23037/-#entry-comment-151948

I think it's fixed
