### ISSUE TITLE
Problem Voting on Comment

### ISSUE THREAD

**Issue by NonITExpert** [hariettem/Artemis#211]
**Describe the bug**
'Problem voting on comment' error appears frequently

**To Reproduce**
Steps to reproduce the behavior. Happens after having voted 2 or 3 times in other posts.
1. Go to a post
2. Scroll down to a comment
2. Tap the middle of comment and slide left.
4. Click on 'up' or 'down' arrow.
5. Vote may or may not register. But after 30 seconds, 'Problem voting on comment' error toast appears.

**Expected behavior**
Slide comment to the left, and select up or down vote.  Vote tally changes based on your selection, with no error.

**Screenshots**
See screenshot

**Smartphone (please complete the following information):**
 - Device: Samsung Note 10+
 - OS: Android 12 One UI 4.1
 - Artemis Version: 2307.06.00.28
![Screenshot_20230706_142900_Artemis](https://github.com/hariettem/Artemis/assets/138516886/cea2bd65-0b21-488f-a411-cc2efc5bb0e2)

**Comment by kruggiero97** [comment]
Heads up, this is a known issue as stated in the known issues section of the onboarding doc :)
