### ISSUE TITLE
Add Option to Toolbar to Refresh While Anywhere on the Page

### ISSUE THREAD

**Issue by NonITExpert** [hariettem/Artemis#212]
**Is your accessibility request related to a problem? Please describe.**
Currently refreshing the page content requires user to scroll back to the top of the page before pulling to refresh is possible. This becomes tedious when you've scrolled through many posts/comments. 

**Describe the solution you'd like**
Please add to the toolbar a button or option for user click to refresh post and comment pages, while anywhere on the page.  Perhaps add a menu to the right of the 'sort' that combines selections for refresh, subscribe/unsubscribe, block magazine, block user etc

**Additional context**

https://github.com/hariettem/Artemis/assets/138516886/27cca5c6-de29-4819-a989-419f97ed218f

**Comment by hariettem** [comment]
added :)
