### ISSUE TITLE
iOS - jump to next parent comment button broken on this thread

### ISSUE THREAD

**Issue by brinazarski** [hariettem/Artemis#216]
iOS 16.5, iPhone XR

https://kbin.social/m/RedditMigration/t/149498/shared-on-Artemis

When I press the down arrow/jump button, instead of going to/down the comments, it jumps up! Or it doesn’t jump at all.

**Comment by geneccx** [comment]
I put more details in #232

**Comment by pvmzqahgyd** [comment]
Please refer to #232
