### ISSUE TITLE
Enhancement - disability pride icon

### ISSUE THREAD

**Issue by brinazarski** [hariettem/Artemis#223]
It’s disability pride month! Maybe we can have an icon with the disability pride flag?

Here’s a link to the preferred flag (the zig zag flag is a migraine and epilepsy trigger) and a brief description of the meaning behind it: https://www.tumblr.com/motionlessmachine/721874650395803649/happy-disability-awareness-month-ann-magill-a

**Comment by pvmzqahgyd** [comment]
What a lovely idea!
