### ISSUE TITLE
Subscribe/Block buttons on the sidebar don't work

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#224]
**Describe the bug**
When viewing the sidebar of a magazine, if you press either the subscribe or block button you will get the error "problem toggling subscription".

**To Reproduce**
1. Go to the sidebar of any magazine
2. Click on subscribe or block 
3. See nothing happen and receive an error 

**Expected behavior**
That the buttons are functional and would allow you to subscribe or block a magazine. 

**Screenshots**
https://github.com/hariettem/Artemis/assets/138167591/a5e2dfc1-fd4e-4595-860a-5fd50b940635

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.6

Update: 2307.08.14.55
(4b538557-d3f5-4b0d-a03e-d3f4cb82fb4a)}

Channel: dogfood

**Comment by hariettem** [comment]
fixed
