### ISSUE TITLE
Link preview toggle not working

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#225]
**Describe the bug**
Clicking the link preview toggle seems to not change anything. I can still see link previews regardless of setting, refreshing the page and force closing the app seems to make no difference. 

**To Reproduce**
1. Go to a post with links
2. Click on settings and toggle off link previews 
3. Go back to post and see that the link previews are still there. 

**Expected behavior**
Turning off link previews on the toggle should prevent you from seeing link previews. 

**Screenshots**
https://github.com/hariettem/Artemis/assets/138167591/6e4e627f-4d85-456d-bc75-1523aefac591

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.6

Update: 2307.08.14.55
(4b538557-d3f5-4b0d-a03e-d3f4cb82fb4a)}

Channel: dogfood

**Comment by Pankakke** [comment]
Based on Version: 0.1.7 Update: 2307.09.19.18
(a6e12517-c706-46ae-a512-8275cef3d225)} Channel: dogfood. 

Toggling link previews seems to work now for comments. Toggling off link previews will still show previews in the original post.

**Comment by hariettem** [comment]
should be fixed
