### ISSUE TITLE
Individual post detail view text

### ISSUE THREAD

**Issue by justinferrell** [hariettem/Artemis#226]
**Describe the bug**
The text for this post runs together

**To Reproduce**
go to https://kbin.social/m/faceting@lemmy.world/t/158524/shared-on-Artemis

**Expected behavior**
I guess the height should expand indefinitely to accommodate in a seemingly infinite amount of text

**Screenshots**
![IMG_3179](https://github.com/hariettem/Artemis/assets/1128985/2724fd19-b43d-44d1-a861-bc9506326cd9)

**Smartphone (please complete the following information):**
 iOS 16, iPhone 14, app version 0.1.6

**Comment by pvmzqahgyd** [comment]
Same on 0.1.5

<img width="450" alt="Screenshot 2023-07-08 at 2 31 08 PM" src="https://github.com/hariettem/Artemis/assets/77108475/7a0c78a0-6813-4024-80b1-0d8a7a258d72">

**Comment by pvmzqahgyd** [comment]
**Below are all related to interface overlaps**

https://github.com/hariettem/Artemis/issues/213
https://github.com/hariettem/Artemis/issues/207
https://github.com/hariettem/Artemis/issues/181
https://github.com/hariettem/Artemis/issues/226
https://github.com/hariettem/Artemis/issues/181
https://github.com/hariettem/Artemis/issues/170

**Comment by hariettem** [comment]
closing, if still an issue, reopen #207
