### ISSUE TITLE
Add a 'show password' clickable eye-thing in the password login field

### ISSUE THREAD

**Issue by RheingoldRiver** [hariettem/Artemis#228]
**Is your feature request related to a problem? Please describe.**
autogenerated passwords are really hard to type & make sure you didnt forget anything, it's a very frustrating experience if you can't see them on mobile

**Describe the solution you'd like**
the eye thing that you can click to show pw

**Describe alternatives you've considered**
maybe login via magic link

**Additional context**
I just retyped my password like 5 times in a row

**Comment by pvmzqahgyd** [comment]
To add to this, I've noticed that some apps are able to match a password request to a relevant entry in your password manager. This is on iOS. I am using 1Password and some apps, when on the login screen, are linking properly and you can tap the autofill icon and autofill with 1Password. Other apps aren't configured properly and are calling localhost which doesn't domain match to the respective entry in 1Password. It would help if the matching works with Artemis.

**Comment by RheingoldRiver** [comment]
Oh good point and also, it's important to systematically test popular password-matching apps. It should work with:

* LastPass
* 1Password
* Bitwarden
* KeePass
* Samsung's native pw manager
* Any other os's native pw managers
* anything else I'm missing

**Comment by NonITExpert** [comment]
Please ensure it also works with Sticky Password

**Comment by RheingoldRiver** [comment]
Closing to open a ticket in /kbin since this is serving a /kbin webpage
