### ISSUE TITLE
Random comments display as faded

### ISSUE THREAD

**Issue by Prouvaire** [hariettem/Artemis#229]
**Describe the bug**
Some comments appear faded - see screenshots.

**To Reproduce**
Unable to reproduce. Seems to happen sporadically.
Manifests in both dark and light themes.

**Expected behavior**
All comments display using the same intensity/colour scheme.

**Screenshots**
3 screenshots attached

**Smartphone (please complete the following information):**
 - Device: LG V60
 - OS: Android 13
 - Version: Artemis 0.1.5, but forgot to capture the build number.  2307.07.21.24 and/or prior.
 
**Additional context**
n/a
![artemis faded posts 3](https://github.com/hariettem/Artemis/assets/138431362/40d4f5ae-c43b-494a-8345-1d2170184293)
![artemis faded posts 2](https://github.com/hariettem/Artemis/assets/138431362/9aab95d0-2ebe-425f-928f-85078c329635)
![artemis faded posts 1](https://github.com/hariettem/Artemis/assets/138431362/4446f9c3-fed5-43fd-a7ed-19e4d1c627f6)

By the way - this seems to be a purely cosmetic bug, so should be prioritised accordingly.

**Comment by geneccx** [comment]
Something weird is going on with the comments in general.

I’ll collapse a comment chain after I’ve read it, but scrolling down I’m noticing that comments I’ve not even seen yet are collapsed.

The jump to next parent comment button also doesn’t seem to work when navigating a long thread - it seems to just stop in the middle.

**Comment by hariettem** [comment]
fixed
