### ISSUE TITLE
Light/Dark mode or theme setting 

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#23]
**Is your feature request related to a problem? Please describe.**
Some Android devices (especially those with older Android versions) do not have a system setting for light/dark mode which applications automatically detect.

**Describe the solution you'd like**
A setting for manually toggling light/dark mode or theme

**Describe alternatives you've considered**
Considering flashing a custom Android distribution with a later version that does have a system light/dark mode, however the process for the specific device model (Xiaomi Mi A1) requires downgrading first and it has soft bricked the device in some prior attempts

**Additional context**
This feature would be very useful during testing.

**Comment by RheingoldRiver** [comment]
Agreed with all of the above, and I'll also add: If you can pick a custom accent color *now*, and eventually there is multi-account switching support, it will be easier later to support theming per-account
