### ISSUE TITLE
Jump button breaks on long threads

### ISSUE THREAD

**Issue by geneccx** [hariettem/Artemis#232]
**Describe the bug**
When viewing long threads, the jump button no longer functions after several taps.

**To Reproduce**
1. Find a post with a long comment chain, e.g. https://kbin.social/m/ArtemisAppPlayground/t/117402/shared-on-Artemis
2. Tap the jump button repeatedly
3. It never makes it to the bottom

**Expected behavior**
Jump button will continue jumping to parent comments until you reach the end of the thread.

**Screenshots**
https://github.com/hariettem/Artemis/assets/1152573/d99bf7bd-5ff2-47f0-add1-71bc1bde5c60

**Comment by ZeroZeroOne-dev** [comment]
This still happens pretty often

https://github.com/hariettem/Artemis/assets/254635/e471ef4a-5578-471a-8a3c-8c9c3c279ba1

If you scroll down manually a few pixels it works again (until it breaks again).
I think it tries to scroll to the post that is already at the top.

**Comment by hariettem** [comment]
fixed
