### ISSUE TITLE
Android Back button doesn't dismiss image preview correctly

### ISSUE THREAD

**Issue by Kraiden** [hariettem/Artemis#236]
**Describe the bug**
Image previews can be dismissed by swiping them away, but the Android hardware (or software I guess) back button causes the preview to dismiss and reopen itself

**To Reproduce**
1. Go to 'home'
2. Click on an image thumbnail to trigger the preview
3. Use the Android back navigation gesture/button of choice

**Expected behavior**
The image preview should be dismissed

**Screenshots**
[recording](https://github.com/hariettem/Artemis/assets/5201226/c8bc3c31-d851-493c-a5c4-4d993fed7ed6)

(also, I didn't pick that image deliberately, but it was too funny not to use it)

**Smartphone (please complete the following information):**
 - Device: Samsung S21 5G (SM-G991B)
 - OS: Android 13
 - Version 0.1.7, Update 2307.09.19.39

**Comment by hariettem** [comment]
love the image LOL. and fixed 👍
