### ISSUE TITLE
Half-swiping away from comments view while loading lets it get stuck

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#25]
**Describe the bug**
While loading a comment view, swiping away halfway causes half of it to remain on-screen

**To Reproduce**
1. Go to a post
2. Swipe halfway back to the previous view
3. See error

**Expected behavior**
Interface returns to the previous view

**Screenshots**
![Screenshot_20230624-114016.png](https://github.com/hariettem/Artemis/assets/11584387/de83887a-1b97-4809-a91a-9589c777f4e5)

![Screenshot_20230624-114047.png](https://github.com/hariettem/Artemis/assets/11584387/fa284d2d-4521-4195-af42-df8a9ca43859)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 9 Pie
 - Version: alpha.1

**Additional context**
May also occur even when the comments view has loaded, quarter-swipes and 1/3rd swipes can sometimes also cause the same issue

**Comment by kruggiero97** [comment]
Can confirm I observe the same behavior on iPhone 14 Pro Max iOS version 16.5.1.
