### ISSUE TITLE
App has weird behavior when checking for updates internally

### ISSUE THREAD

**Issue by Uprise42** [hariettem/Artemis#257]
**Describe the bug**
On the first try the app crashes. Subsequent tries result in screen flashing and menu refreshing 

**To Reproduce**
1. Go to settings
2. Click on check for updates
3. If the app crashes, repeat the steps

**Expected behavior**
Before the menu would say either “up to date” or downloading

**Screenshots**
https://github.com/hariettem/Artemis/assets/58179605/1afa0014-6eaa-42bc-8ae7-6470d9db6f60

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - OS: iOS 17.0
 - Version: 0.1.7

Update: 2307.10.20.24
(aedcf0b1-c0de-43d4-8506-c2943e18c621)}

Channel: preview

**Comment by pvmzqahgyd** [comment]
Persists with newer app version, see issue https://github.com/hariettem/Artemis/issues/272
