### ISSUE TITLE
Long-ish posts with multiple headers are cutoff and overlap with the UI, also off-setting collapsed comments

### ISSUE THREAD

**Issue by Amongog** [hariettem/Artemis#259]
**Describe the bug**
A long-ish post containing 4 headers fails to display completely, and cuts off, overlapping some text over the rest of the UI. The cutoff is a bit after the 3rd header.

Additionally, when displaying the post, collapsed comments are offset and still show a bit of the text that should be collapsed.

In the [test post](https://kbin.social/m/ArtemisAppPlayground/t/172561/Testing-if-posts-with-multiple-headers-causes-issues) it happens that the post overflows behind the comment section and continues below it (see third picture)

**To Reproduce**
1. Go to https://kbin.social/m/freemediaheckyeah@lemmy.fmhy.ml/t/172179/Defederation-Policy or the test post I created: https://kbin.social/m/ArtemisAppPlayground/t/172561/Testing-if-posts-with-multiple-headers-causes-issues
2. See error

**Expected behavior**
The full text of the post should be displayed.

**Screenshots**
![WhatsApp Image 2023-07-10 at 17 31 33](https://github.com/hariettem/Artemis/assets/70033730/48884c7e-acd3-4c7e-8c4e-331e23909d91)
![WhatsApp Image 2023-07-10 at 17 31 00](https://github.com/hariettem/Artemis/assets/70033730/d825b339-4d59-480a-9e52-cc091dd3d60d)
![WhatsApp Image 2023-07-10 at 17 42 19](https://github.com/hariettem/Artemis/assets/70033730/db54dd30-1b4e-4dae-8e73-d2867b4742e7)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52
 - OS: Android
 - Version 13

**Comment by hyplex1** [comment]
Adding the same experience from a:

Galaxy S23, Android v13

For lack of the right terms, the widget that houses the OP doesn't dynamically expand to push the comments widget down and the two are overlapped.

![artemis post text cutoff 1](https://github.com/hariettem/Artemis/assets/139184881/1a962c61-fe75-4a54-9b9f-1943128ebea9)
![artemis post text cutoff 2](https://github.com/hariettem/Artemis/assets/139184881/d1e97398-543d-41e2-81c7-328b0cc489ca)

**Comment by Daleeburg** [comment]
Would like to add this is also happening on:

iPhone 14, iOS 16.5.1

![image](https://github.com/hariettem/Artemis/assets/129229428/943f25cd-0f54-4261-a228-b903326cfc47)

Example post link:
https://kbin.social/m/maliciouscompliance@lemmy.world/t/172646/shared-on-Artemis

Steps to reproduce:
1. Go to any long post
2. Scroll down

**Comment by kruggiero97** [comment]
Seems related to #197

**Comment by jcrabapple** [comment]
Seeing this on a recent post as well.

https://dmv.pub/m/technology@lemmy.world/t/1277/shared-on-Artemis


![Screenshot_20230711-071231.png](https://github.com/hariettem/Artemis/assets/13261654/fe939c63-fdb0-4d9d-b957-b5ac2c19dee1)

**Comment by aitmanga** [comment]
Yup, seems to happen with long enough posts. I got it on this one too: https://kbin.social/m/maliciouscompliance@lemmy.world/t/172646/shared-on-Artemis
![image](https://github.com/hariettem/Artemis/assets/31661702/53baa5c6-ea49-4cff-989d-acb2031f2cb4)

**Comment by LazaroFilm** [comment]
Looks like it's the link cards that create this but. This is pretty critical and app breaking as any post with links becomes unreadable.

**Comment by kruggiero97** [comment]
> Looks like it's the link cards that create this but. This is pretty critical and app breaking as any post with links becomes unreadable. 

Seems to be length of post. Hariette is working on it, but seems to be a stubborn bug. Source from Discord:
![image](https://github.com/hariettem/Artemis/assets/49291963/3dbab39e-3ad2-47e6-a769-62a122cb280b)

**Comment by kruggiero97** [comment]
> Looks like it's the link cards that create this but. This is pretty critical and app breaking as any post with links becomes unreadable. 

See also #197
