### ISSUE TITLE
Settings button doesn’t scroll all the way to end

### ISSUE THREAD

**Issue by its-yourmom** [hariettem/Artemis#262]
**Describe the bug**
When I click on the settings icon and scroll down, there is a large black space and then just below I can make out “dotted line” and that’s as far down as I can go.

**To Reproduce**
1. Go to “Settings”
2. Click on your user profile
3. Go back to settings and try to scroll to the bottom
4. unable to finish scrolling? 

**Expected behavior**
I expect to get to the very end without stopping or meeting resistance.

**Screenshots**

**Smartphone (please complete the following information):**

https://github.com/hariettem/Artemis/assets/139178936/5142f058-5268-4c81-afb8-45d69547dee8

 - Device: iPhone 11 Pro
 - OS: iOS version 16.1.1
 - Version [e.g. alpha.1] not sure. Just got access this afternoon around 4 pm ish?

**Additional context**
This is my first attempt at “GitHub” so if this isn’t at all right… or filled out correctly… please ask me to do it again. Thank you!

**Comment by RheingoldRiver** [comment]
hey @its-yourmom can you still reproduce this on the current version?

**Comment by its-yourmom** [comment]
This issue was fixed! How do I close this ticket?

**Comment by its-yourmom** [comment]
I figured out how to close it! Thank you for fixing this issue!
