### ISSUE TITLE
Inconsistent UX when viewing images

### ISSUE THREAD

**Issue by Daleeburg** [hariettem/Artemis#264]
**Describe the bug**
When opening an image, the ONLY way to close it is to swipe up or down. This is inconsistent of the left to right swipe used through out the UX to return to the previous view. It is not intuitive to swipe up or down to close the image versus tapping an “x” or tapping outside of the image. I felt “lost” when opening an image and didn’t understand how to close it till experimenting to discover swipe up or down. 

**To Reproduce**
1. Open an image by clicking directly on it
2. Try swiping from left to right
3. Try finding an X
4. Try tapping outside of the image 
5. Try any other methods besides swiping up or down. 

**Expected behavior**
As the left to right swipe is used through the UX to navigate back, it would be expected that the left to right swipe would also close the image. Baring use of a swipe, would also expect that clicking outside of the image or a “x” in a corner would close the image. 

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/129229428/9a2181c8-1757-43c2-a417-d9b8310de642)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5.1
 - Version 0.1.7 (1)

**Additional context**
This might be more of enhancement, just trying to prevent feelings of confusion when a user first uses the app.

**Comment by terevos** [comment]
I am seeing the same on Android. 

***In addition, the 'Back' button (or gesture) closes the image for a second, but then it pops back up.***

Device: Pixel 6
OS: Android 13
Version: 0.1.7

**Comment by hariettem** [comment]
> I am seeing the same on Android.
> 
> _**In addition, the 'Back' button (or gesture) closes the image for a second, but then it pops back up.**_
> 
> Device: Pixel 6 OS: Android 13 Version: 0.1.7

Can you post update number?

Back button fixed was apply on an update recently. And was confirm fixed.

Can't repro back button issue right now.

**Comment by hariettem** [comment]
I'll add a close button. Swiping left of right is going to be used for seeing the next image posts, so can't use it for closing out. But tapping outside can be implemented.

**Comment by terevos** [comment]
Update: 2307.11.01.55

**Comment by Daleeburg** [comment]
This has been addressed.  Thanks!
