### ISSUE TITLE
I get taken to “The Gaurdian” website when I click the Artemis app icon on my Home Screen.

### ISSUE THREAD

**Issue by its-yourmom** [hariettem/Artemis#268]
**Describe the bug**

I click on the Artemis App icon on my Home Screen and I get immediately taken to “The Guardian” website. But then I can swipe down and get to the home of Artemis.

**To Reproduce**
1. Go to my IPhone Home Screen.
2. Click on Artemis App Icon
3. Immediately get taken to The Guardian

**Expected behavior**

I’d expect to be taken to Artemis App Home Screen. Not to “The Guardian”.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: version 16.1.1
 - Version [e.g. alpha.1] still not sure as I can’t scroll to bottom of settings button to obtain this info. But app was downloaded on 07.10.2023 around 4 pm.

**Additional context**
Thank you!

**Comment by RheingoldRiver** [comment]
Looks like this was solved in discord: https://discord.com/channels/1118996335119569036/1125093022179278908/1128198395778056192

**Comment by its-yourmom** [comment]
Yes, this was solved. Apparently artemis remembers the last thing you saw and immediately takes you there when opening the app. ( don’t really remember going to the guardian) , but after clicking on other things in the app and closing it down, I was taken to the Artemis Home Screen and not the guardian. Sorry for an extra bug report! Appreciate you!

**Comment by kruggiero97** [comment]
Closed because it seems to be solved based on the other comments.
