### ISSUE TITLE
Logging in from a non-official kbin instance doesn't work

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#27]
**Describe the bug**
Logging in with an account from a non-official kbin instance breaks the application in the following ways:

- If an account from the official kbin instance uses the same email address, Artemis will display the username from that account instead
- Home view infinitely loads
- Artemis will only accept the full email, not just the username

**To Reproduce**
1. Go to 'Profile'
2. Enter instance domain
3. Enter email address and password
4. See erroneous username
5. Go to 'Posts'
6. See infinitely loading Home view

**Expected behavior**
Successful login from a non-official instance with the correct username and a working Home/Posts view

**Screenshots**
`[Due to involving entry of sensitive login information, no screenshots nor recordings could be provided.]`

**Smartphones (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 15.7.6
 - Version: alpha.1
&nbsp;
 - Device: Xiaomi Mi A1
 - OS: Android 9 Pie
 - Version: alpha.1

**Additional context**
Need to make another account with a different email address to fully determine what's going on, as the bug seems rather vague as to what it is actually exhibiting.

**Comment by hariettem** [comment]
Care to try again?

**Comment by hariettem** [comment]
fixed
