### ISSUE TITLE
Unable to use text cursor while typing in post/reply text field

### ISSUE THREAD

**Issue by Grimlo9ic** [hariettem/Artemis#270]
**Bug Description**
When typing in a post/reply, navigating the text while actively typing is currently not supported - you can't swipe or touch and hold the cursor to move it, and the draggable handle does not appear.

Here, the keyboard is up, and while I can see the cursor at the end of my reply, I cannot drag/move it unlike in other Android apps:

![](https://i.imgur.com/FcqdV2a.jpg)

On the other hand, if you exit out of the keyboard, then you can start manipulating the cursor again (as well as seeing more than 2 lines in the text field). But at that point you run into issue #248:

![](https://i.imgur.com/u6HyZEi.jpg)

**Steps to Reproduce**
1. Create a post or reply.
2. Start typing in a longer response than 2 lines (the example used 5 paragraphs of Lorem ipsum).
3. Attempt to manipulate the cursor as text entry is ongoing.
4. Exit the keyboard, then reattempt to manipulate the cursor.

**Expected Behavior**
Here's the native messaging app on my phone, and here you can manipulate the text cursor while you're typing something in:

![](https://i.imgur.com/YGXn7Lw.jpg)

![](https://i.imgur.com/KHScbxA.jpg)

**Smartphone Details**
 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - App Version: 0.1.7
 - Update: 2307.10.16.09

**Comment by creativeghostfish** [comment]
Same issue here (the first part). Did not seem to have any issues with the second part; after I backed out of keyboard and tapped the comment it brought the keyboard back up and I was able to move the cursor as in other apps. (I hope that makes sense)

Pixel 5
Android 13
Version: 0.1.7
Update: 2307.11.21.26
(cfe04f33-ec17-4743-bb3f-027b7cdf28d3)}

Channel: preview

**Comment by hariettem** [comment]
fixed!

**Comment by Grimlo9ic** [comment]
Hi @hariettem! I assume the fix is only live in v0.2.0 branch, correct? I'm still using kbin.social so I won't be able to validate this one from my end for some time, at least until the public beta is released.
