### ISSUE TITLE
Save image to camera roll

### ISSUE THREAD

**Issue by SARankDirector-Minecraft** [hariettem/Artemis#275]
**Describe the solution you'd like**
Press and hold on image. Have a pop up that allows you to save the image

Have a "save image" button in the share sheet (the menu opened with the share button).

**Additional context**

Press and hold example (safari, iOS ):
![image](https://github.com/hariettem/Artemis/assets/16199488/1dbd1b8e-47f4-42ae-86ec-aa219b14ca3f)

Share sheet example (Twitter, iOS):
![image](https://github.com/hariettem/Artemis/assets/16199488/e17e8b30-377b-4e9e-b03b-f7b86e544053)

**Comment by hariettem** [comment]
added!
