### ISSUE TITLE
Image view translucent background edge visible while exiting it

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#28]
**Describe the bug**
When closing the image view, the top edge of the translucent background can be seen sliding out

**To Reproduce**
1. Open an image
2. Swipe down on image to dismiss it
3. See top edge of translucent background slide down to disappear 

**Expected behavior**
Translucent background fades away instead of following image in sliding offscreen

**Screenshots/Recordings**

https://github.com/hariettem/Artemis/assets/11584387/3dc8082d-9064-4035-9899-b2a3f5998697

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 15.7.6
 - Version: alpha.1

**Additional context**
Testing ongoing on Android

**Comment by win8linux** [comment]
Bug replicated on Android, where it is more visible in light mode:

https://meanderspace.v6.rocks/nextcloud/s/4nnsDsSALqPCYed

- Device: Xiaomi Mi A1
- OS: Android 9 Pie
- Version: alpha.1

**Comment by hariettem** [comment]
Using seperate issue to track this. Going to rewrite that part
