### ISSUE TITLE
Every parent comment is incorrectly labelled as OP

### ISSUE THREAD

**Issue by geneccx** [hariettem/Artemis#281]
**Describe the bug**
Every parent comment is incorrectly labelled as OP

**To Reproduce**
1. Open the comments on any post

**Expected behavior**
Only the real OP is labelled as such.

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/1152573/24adb5c8-7e87-4341-9006-e14777a1578f)

**Smartphone (please complete the following information):**
 - Version [e.g. alpha.1]

Version: 0.1.7

Update: 2307.11.21.05
(d0a0df46-821e-4e70-ad0e-427fe3eccc1c)}

Channel: preview

**Additional context**

**Comment by kruggiero97** [comment]
Same issue on

Version: 0.1.7
Update: 2307.11.21.10
(30de5b31-0df4-4823-a2b6-4932494a20df)}
Channel: dogfood

![image](https://github.com/hariettem/Artemis/assets/49291963/16cc1429-997c-468e-83a0-8e11b1823fb8)

**Comment by geneccx** [comment]
Appears to be fixed in

Version: 0.1.7

Update: 2307.11.21.26
(5cc7869d-31c9-4e30-b24f-ba3b490dc10b)}

Channel: preview
