### ISSUE TITLE
Text obscured by link containers

### ISSUE THREAD

**Issue by VasyaSovari** [hariettem/Artemis#283]
[**Describe](url) the bug**

a lot of overlap in longer posts with lots of links

**To Reproduce**
1. Go to '...' : a long form post with links
2. Click on '....' , nothing, just observe

**Expected behavior**

expected to be able to view all the text in the post without any of it being blocked by link boxes

**Screenshots**

![IMG_0054](https://github.com/hariettem/Artemis/assets/14034202/47615b6d-7574-4508-85dd-ebfea38ad07e)

**Smartphone (please complete the following information):**
 - Device: iPad 5
 - OS: iOS 16.6
 - Version Artemis 0.1.7

**Additional context**

**Comment by kruggiero97** [comment]
Likely related to #197, #256, #248, #259, etc

**Comment by VasyaSovari** [comment]
Yup, seems right. Will close the issue as a duplicate
