### ISSUE TITLE
No way to switch between home and all

### ISSUE THREAD

**Issue by Uprise42** [hariettem/Artemis#289]
**Describe the bug**
Artemis opened to m/all and has no way to switch back. The button that should be there is not

**To Reproduce**
1. Open Artemis
2. See bug

**Expected behavior**
There should be a button to switch between home and all

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/58179605/ea941054-0da8-4793-873a-c2aab78191f4)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.0
 - Version Version: 0.1.7

Update: 2307.12.01.18
(9ca3ce18-fcd4-4a5f-9601-b14639a015f6)}

Channel: preview

**Additional context**

**Comment by Daleeburg** [comment]
Able to reproduce.

iPhone 14
iOS 16.5.1
V: 0.1.7 (1)

**Comment by geneccx** [comment]
Are you logged in?

**Comment by Daleeburg** [comment]
> Are you logged in?

I have been running 2 instances, one logged in, one not, so got them confused. I do believe this is functionally as intended.

**Comment by pvmzqahgyd** [comment]
@Uprise42 can you please respond so we know whether this can be closed? Thanks.
