### ISSUE TITLE
Selecting Magazine, going back, and selecting another magazine does not work. 

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#29]
**Describe the bug**
Selecting Magazine, going back home, and selecting another magazine does not work. 

[Video](https://files.catbox.moe/hyxg5k.mp4)

**To Reproduce**
1. Go to 'Home' Dropdown
2. Select Magazine
3. Swipe to go back
4. Select Magazine
5. See error

**Expected behavior**
Show selected magazine

**Screenshots**
[Video](https://files.catbox.moe/hyxg5k.mp4)

**Smartphone (please complete the following information):**
iOS 16.5 - iPhone Xs Max

**Additional context**

**Comment by hariettem** [comment]
Fix tested and working. Will deploy in next push.
