### ISSUE TITLE
Add features to the 'swipe-left' menu on home/all feed

### ISSUE THREAD

**Issue by McBinary** [hariettem/Artemis#292]
**Is your feature request related to a problem? Please describe.**
There appears to be no clear/efficient way to access user profiles/magazine without digging into posts or searching directly for them.

**Describe the solution you'd like**
I thought that adding these shortcuts to the swipe-left menu on parent post in the home/all space would allow a quick and efficient way of reaching these places. Pull left gesture could still function for voting, but swiping "all the way" to the left could allow icons that link to the following:
- Visit the poster's user profile ('head icon' or something identifiable)
- Bookmark/save the post (bookmarks are currently working on kbin 2/3 dev instances) (star or bookmark icon)
- Visit parent magazine of the post ( magazine icon or scrape official magazine avatar?)

**Describe alternatives you've considered**
A long press menu would work similarly without needing to dig into other menus.

**Additional context**
Relay for Reddit had similar gesture shortcuts, here are those images for context. Swipe left bar, and the menu that opens for "more"
![image](https://github.com/hariettem/Artemis/assets/139311952/e0cb30a7-77bc-4e38-9145-754d4604fd19)
![image](https://github.com/hariettem/Artemis/assets/139311952/10d6eb02-d5cd-4ac7-8be2-e97ccb79e443)

**Comment by hariettem** [comment]
This was implemented as a menu. But could expand to add mark as ready and blocking/subscribing to it too.
