### ISSUE TITLE
Replying to long comment cause username to encroach on text box

### ISSUE THREAD

**Issue by Daleeburg** [hariettem/Artemis#294]
**Describe the bug**
Replying to some very long comments causes the username of the comment you are replying to to encroach into the text reply box

**To Reproduce**
1. Go to this comment: https://kbin.social/m/ArtemisAppPlayground/t/180451/Testing-Time-to-post-comments#entry-comment-718280
or this comment: https://kbin.social/m/ArtemisAppPlayground/t/180451/Testing-Time-to-post-comments#entry-comment-726424

3. Tap to Reply to the comment

**Expected behavior**
Expect the username to not encroach on the comment reply text box. 

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/129229428/12d3a7dd-bd69-43fe-9d93-4d5a4f4c783c)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5.1
 - Version Version: 0.1.7
Update: 2307.12.02.46
(a66495ca-43a7-4828-806e-d161c5d4a0ad)}
Channel: preview

**Additional context**

**Comment by hariettem** [comment]
fixed!
