### ISSUE TITLE
Posting extremely long comments fails with no error

### ISSUE THREAD

**Issue by Daleeburg** [hariettem/Artemis#295]
**Describe the bug**
When attempting to posting extremely long comments, the posting fails, but there is no error. 

**To Reproduce**
1. Generate a lot of text.  Using 20 paragraphs from here https://randomwordgenerator.com/paragraph.php
2. Copy text from website to comment box on any post
3. Click submit, 
4. wait for request to seemingly time out
5. See error

**Expected behavior**
I am guessing that this is actually a limitation of Kbin comment sizes.  Ideally a warning would be displayed before posting letting the user know the comment is too long. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5.1
 - Version Version: 0.1.7

Update: 2307.12.02.46
(a66495ca-43a7-4828-806e-d161c5d4a0ad)}

Channel: preview

**Additional context**

**Comment by hariettem** [comment]
fixed
