### ISSUE TITLE
Copying comment text does not copy blank new lines

### ISSUE THREAD

**Issue by Daleeburg** [hariettem/Artemis#296]
**Describe the bug**
When copying the text of a post and pasting it into another post, the copy function does not preserve any blank new lines. 

**To Reproduce**
1. Create or find as comment with new lines between paragraphs
2. Long press on the comment, select “copy text”
3. Reply to the comment
4. Paste the copied text into the reply box
5. See error

**Expected behavior**
Formatting/Blank lines to persist through the copy

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/129229428/9cfb5346-7468-4059-a29b-d3aa47bcd913)

**Smartphone (please complete the following information):**
 - Device: iphone 14
 - OS: iOS 16.5.1
 - Version Version: 0.1.7

Update: 2307.12.02.46
(a66495ca-43a7-4828-806e-d161c5d4a0ad)}

Channel: preview

**Additional context**
None

**Comment by hariettem** [comment]
fixed
