### ISSUE TITLE
Posting long comments takes a long time

### ISSUE THREAD

**Issue by Daleeburg** [hariettem/Artemis#297]
**Describe the bug**
When posting very long comments it takes a long time to post. While a couple word comment will post in about 3-4 seconds, very long comments take 25+ seconds

**To Reproduce**
1. Create a very long comment using 10 paragraphs from https://randomwordgenerator.com/paragraph.php
2. Tap to post the comment
3. Start a timer 
4. See error (if the post fails, see #295 , shorten the comment and repeat)

**Expected behavior**
While larger comments do have more data, we are talking Kbs not Mbs, so I would expect them to post at close to the same speed. 

**Screenshots**
N/A, need to figure out how to do a screen recording

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5.1
 - Version Version: 0.1.7

Update: 2307.12.02.46
(a66495ca-43a7-4828-806e-d161c5d4a0ad)}

Channel: preview

**Additional context**
A bunch of testing in this thread: https://kbin.social/m/ArtemisAppPlayground/t/180451/shared-on-Artemis

This should probably be low priority as the functionally works, it’s just slow. I’m guessing it’s something with a markup parser.

**Comment by hariettem** [comment]
fixed
