### ISSUE TITLE
Very little room to do the open sidebar swipe action 

### ISSUE THREAD

**Issue by ZeroZeroOne-dev** [hariettem/Artemis#298]
**Describe the bug**
When you want to open a magazine sidebar by swiping in from the right you have very little room to do so.
You have to do it exactly in the empty space between posts or otherwise you will open the post quick actions instead.

**To Reproduce**
1. Go to a community feed
2. Try to open the side bar by swiping in from the right
3. Instead the post quick actions open

**Expected behavior**
The sidebar opens

**Screenshots**
https://github.com/hariettem/Artemis/assets/254635/ced60c57-a28b-430a-a58a-12c284f39c9d

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro max
 - OS: iOS 16.5.1
 - Version: 0.1.7 - 2307.12.02.46

**Additional context**
Maybe move the swipe action to the top bar ? (on the magazine name maybe?)

**Comment by hariettem** [comment]
Is it any better with latest update? The right edge was cleared out a bit. Lmk or I can make the space bigger

**Comment by ZeroZeroOne-dev** [comment]
Just tested, feels perfect now, nice 😀
