### ISSUE TITLE
Android Material You Dynamic Theme Colors

### ISSUE THREAD

**Issue by Amongog** [hariettem/Artemis#301]
**Describe the solution you'd like**
Many apps in Android now have compatibility with Material you Dynamic Color Pallets.
Artemis already has a modern UI with many color options. I think this option would make a great addition to the theme color list.

**Additional context**
Sync for Reddit _(May it rest in peace)_ had included this feature in one of its last updates, and I absolutely loved the way it adjusted colors to match my system color pallet.

Here are some examples I can find on the web, since I don't have access to the app anymore 🥲

![image](https://i.imgur.com/QHZVTXL.jpg)
![image](https://i.imgur.com/c1iz0cC.jpg)
![image](https://i.imgur.com/K2gfpfk.jpg)

**Comment by NonITExpert** [comment]
I would love to see this too!

**Comment by hariettem** [comment]
added!
