### ISSUE TITLE
Auto-Upvote on Boost

### ISSUE THREAD

**Issue by LazaroFilm** [hariettem/Artemis#305]
I never boost without upvoting. 
Creating a setting to upvote automatically when boosting would save a tap.

**Comment by Daleeburg** [comment]
This maybe should be a selectable option!

**Comment by LazaroFilm** [comment]
> This maybe should be a selectable option!

Yes absolutely should be a setting toggle (can be off by default).

**Comment by LazaroFilm** [comment]
Also, this mechanism would match Imgur's 💚 action that also ads an upvote with the like.

**Comment by hariettem** [comment]
added!
