### ISSUE TITLE
Sort and collection menu buttons overflow the line separating the header from posts

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#308]
**Describe the bug**
The buttons to change your sort type and button to bring up the subscribe, favorite, block, etc. options overflow, hiding some of the line separating the header from the posts themselves

**To Reproduce**
1. Go to any magazine
2. See error

**Expected behavior**
The line separating the header from posts to be fully visible.

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/49291963/e9139ead-23de-4347-b2e8-d299353790cf)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.7
 - Update: 2307.13.17.12
 - (4d307f00-4745-47f9-8635-407a8358a78a)}
 - Channel: dogfood

**Comment by hariettem** [comment]
fixed
