### ISSUE TITLE
You can not pan a zoomed image up/down

### ISSUE THREAD

**Issue by Boothin** [hariettem/Artemis#309]
**Describe the bug**
If you are viewing an image and zoom, you can only pan the image right/left. If you try to pan up/down the image will re-center itself vertically.

**To Reproduce**
1. Click on any image that opens in the in-app image viewer
2. Zoom in until the image is larger than your phone screen (it actually does not need to be larger than the screen, but it's only really an issue if it is)
3. Try to move the image up or down to view a cut off portion of the image
4. When you release your finger, the image will re-center itself vertically

**Expected behavior**
The image should stay panned in the direction you pull it so you can see the top/bottom of the image.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Version 0.1.7 Update 2307.14.00.23

**Comment by Daleeburg** [comment]
Able to reproduce on iPhone!

Check: https://kbin.social/m/memes@lemmy.ml/t/191934/shared-on-Artemis


iPhone 14
iOS 16.5.1
Version: 0.1.7

Update: 2307.13.16.49
(2ff8f992-0334-4f5d-a2a5-9e7f1625954c)}

Channel: preview

**Comment by hariettem** [comment]
fixed
