### ISSUE TITLE
Upvote/Downvote/Boost actions on swipe of post

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#31]
**Is your feature request related to a problem? Please describe.**
I described expected Apollo behavior [here](https://github.com/hariettem/Artemis/issues/30). 

**Describe the solution you'd like**
Apollo-like behavior for interacting with posts. Pull left 1/5th of the way, and release to upvote. Pull left 2/5th, downvote. User is made aware of effect with haptic feedback.
There is no swipe right - But following Apollo, this should save or boost the post. This depends on how Ernest will deal with what role boosting gets in kbin.

**Comment by pvmzqahgyd** [comment]
I would add to the request that it's made customizable. Some users are left-handed and it makes a difference I imagine.

**Comment by Trez-zerT** [comment]
I would also appreciate customisability here. As a leftie, I basically need to two-hand my Pro Max iPhone to reach boost/up/down.
