### ISSUE TITLE
Trying to pan an image vertically too far closes the image

### ISSUE THREAD

**Issue by Boothin** [hariettem/Artemis#310]
**Describe the bug**
When viewing an image in the in-app image viewer, trying to move the image vertically more than about 30% of the screen height closes the image.

**To Reproduce**
1. Open an image in the in-app image viewer
2. Try to drag the image vertically moving your finger at least ~30%+ of the screen's height
3. This also happens if the image is zoomed in enough that you can drag the image diagonally, as long as the vertical distance is far enough
4. The image viewer will close

**Expected behavior**
The image viewer should stay open

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Version 0.1.7 Update 2307.14.00.23

**Comment by Daleeburg** [comment]
Able to reproduce.  Check this post:

https://kbin.social/m/memes@lemmy.ml/t/191934/shared-on-Artemis

iPhone 14
iOS 16.5.1
Version:Version: 0.1.7

Update: 2307.13.16.49
(2ff8f992-0334-4f5d-a2a5-9e7f1625954c)}

Channel: preview

**Comment by Daleeburg** [comment]
Also, this is probably related to #309
