### ISSUE TITLE
Font scaling causes interface components shifting

### ISSUE THREAD

**Issue by pvmzqahgyd** [hariettem/Artemis#312]
When font scaling is increased, some interface components shift
iOS 17 PB1 / Artemis 2307.14.01.38

**Comment by pvmzqahgyd** [comment]
<img width="423" alt="Screenshot 2023-07-14 at 10 41 42 AM" src="https://github.com/hariettem/Artemis/assets/77108475/9c758e4f-43c6-4126-9eb1-b554f889617b">

**Comment by pvmzqahgyd** [comment]
<img width="423" alt="Screenshot 2023-07-14 at 10 41 57 AM" src="https://github.com/hariettem/Artemis/assets/77108475/ae3ed9db-6731-415e-bcae-d50ece21cc84">

**Comment by pvmzqahgyd** [comment]
<img width="423" alt="Screenshot 2023-07-14 at 10 42 10 AM" src="https://github.com/hariettem/Artemis/assets/77108475/3256488d-5822-4671-80f7-ad92a35b223f">

**Comment by hariettem** [comment]
should be fixed. reopen if u experience this
