### ISSUE TITLE
Autohide comments downvoted below a limit

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#313]
**Is your feature request related to a problem? Please describe.**
Heavily downvoted comments being open, cluttering the comment view. Very annoying, especially when they contain unhinged content.

**Describe the solution you'd like**
Settings for autohiding downvoted comments; a toggle and a number field for entering the negative point threshold that a comment needs to reach before the feature is triggered.

**Describe alternatives you've considered**
Manually collapsing heavily downvoted comments can get rather cumbersome on more controversial or spammed posts.

**Additional context**
This was a feature in reddit and RedReader that was rather useful at cleaning up comment sections.

**Comment by hariettem** [comment]
just added. tho setting for specific count will have to be a seperate feeature request
