### ISSUE TITLE
Hot feed excluding readed threads

### ISSUE THREAD

**Issue by mizzyc** [hariettem/Artemis#314]
**Problem:**
One of the things I miss the most from Reddit is that anytime my homepage was filled with new unread content.
But Kbin's Hot feed ignore the fact that you already saw a thread and keeps showing you the same content, just based on a time filter (for example, Hot content in the last 3 hours).

**Solution:**
Have an option to hide from the "Hot" feed the content that already has been seen (read or just scrolled). So the feed would always have new content, making users spend more time on app.

**Additional context:**
To be honest, I don't know if it's a viable feature. It's clear to me that it have a lot of impact on performance, since Artemis would need to get all posts, hide one by one and load the ones that are new to the user. Buuuut, that'd be an amazing feature and would help a lot to use Kbin more and more.

**Comment by hariettem** [comment]
theres a hide seen posts option

**Comment by hariettem** [comment]
but its everywhere. reopen this issue if its important to limit the feed
