### ISSUE TITLE
Changing magazines too many times without going back causes app to slowdown and eventually crash

### ISSUE THREAD

**Issue by Boothin** [hariettem/Artemis#315]
**Describe the bug**
Since everytime you use the magazine chooser in the top left to go to Home/All/some magazine it takes you forward to a new page, doing so too many times without going back will cause the app to slow down. Once you have gone far enough, if you force close the app and try to start it again, it will not load and just crash on startup.

**To Reproduce**
1. Click the magazine selector on the top left
2. Pick any option i.e. home, all, or any magazine
3. Keep navigating to different options in the magazine selector WITHOUT going back
4. After about 10-15 magazines, the slowdown became very noticeable, with 0.5+ second delay on my clicks.
5. After about 30 magazines, closing the app and trying to start it again will cause the app to crash during load. Clearing the app storage is necessary to get the app to start again.

**Expected behavior**
The number of "layers" should be limited so that the app isn't saving a large back history and crashing. 

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Version 0.1.7 Update 2307.10.03.00

**Comment by hariettem** [comment]
improved with update today
