### ISSUE TITLE
Inbox tab disappears.

### ISSUE THREAD

**Issue by TheRealTorafugu** [hariettem/Artemis#316]
**Describe the bug**
This bug prevents users from accessing a reply to a comment, and then removes the "Inbox" tab completely.

**To Reproduce**
1. Go to Inbox
2. Tap on someone's reply to one of your comment.
3. Wait for the app to refresh
4. See that the Inbox tab is missing.

**Expected behavior**
A page showing the comments to the post that you commented on, with the reply from the inbox highlighted.

**Screenshots**
![Screenshot_20230714_235402_Artemis](https://github.com/hariettem/Artemis/assets/70166840/912cc92d-af84-4b4d-8ff8-a32d10bde90a)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A03s
 - OS: Android 13
 - Version 0.1.7

**Additional context**
Restarting the app did not fix it.

**Comment by Boothin** [comment]
This is likely an issue with kbin logging everyone out today. You can see your profile tab doesn't have your username, meaning you are not logged in.
