### ISSUE TITLE
Clicking on an image post and then swiping back will occasionally result in the app freezing when scrolling

### ISSUE THREAD

**Issue by ex-youth** [hariettem/Artemis#319]
**Describe the bug**
Clicking on an image post, swiping back to the feed, and then scrolling will sometimes result in a momentary freeze. 

![IMG_1845](https://github.com/hariettem/Artemis/assets/137928675/c9ce8053-f876-46a2-b85c-d79daaef8ce5)

**Comment by hariettem** [comment]
fixed
