### ISSUE TITLE
Inbox goes directly to comment.

### ISSUE THREAD

**Issue by LazaroFilm** [hariettem/Artemis#321]
**Describe the bug**
When clicking on a reply in the inbox it goes to the top of the post instead of scrolling down to the reply. 

**To Reproduce**
Tap a reply in you inbox

**Expected behavior**
When tapped goes to the post and scrolls down to the comment.

**Comment by pvmzqahgyd** [comment]
@LazaroFilm On what device, what OS, and which app version?

**Comment by LazaroFilm** [comment]
Version: 0.1.7

Update: 2307.17.19.35
(3ba5c859-9286-4805-9517-73aa39817c0b)}

Channel: preview

16.5.1 (c) iPhone 14 Pro

**Comment by hariettem** [comment]
fixed
