### ISSUE TITLE
Trying to Back Button/Swipe from Sidebar Crashes App

### ISSUE THREAD

**Issue by Alaric323** [hariettem/Artemis#322]
**Describe the bug**
Trying to exit the sidebar of any community with a swipe (from either direction on Android) causes the app to crash.  EDIT: (~~Combined with issue #238, it is impossible to leave the sidebar and return to the community without first returning to the previous post, then navigating back.~~) Didn't realize there was a gesture control for opening/closing sidebar, I've been doing it through the meatball button this whole time.  Crash issue DOES still apply though when swiping with system back method.

**To Reproduce**
1. Open any community sidebar
2. Attempt to close sidebar via system "go back" method
3. Artemis crashes

**Expected behavior**
To close the sidebar

**Screenshots**
Can't attach via phone at the moment, will add a followup comment later if needed.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - OS: Android 13 with OneUI
 - Version: 0.1.7
Update: 2307.17.19.35
(325a7fc0-594b-4dcd-91cd-e5d23fec7edc)}
Channel: preview

**Comment by hariettem** [comment]
fixed
