### ISSUE TITLE
Home feed inaccessible - only able to view individual magazines or all

### ISSUE THREAD

**Issue by drewbs-b** [hariettem/Artemis#325]
For the past week or so, since turning on discovery mode for home, I am unable to access my home feed at all. Selecting home just gives me “All”

I tried reinstalling the app, and that worked for one session but upon returning to the app the issue persisted. 

 - Device: iPhone 13 Pro
 - OS: iOS
 - Version [e.g. alpha.1] 16.6 Beta

**Comment by pvmzqahgyd** [comment]
@drewbs-b Try this: Uninstall the app, and reinstall again. Make sure app is updated to latest version (at the moment of this comment it's 0.1.7 / 2307.17.19.35) by going to in-app Settings > Check for Updates (do it a few times), restart the app, and login with your kbin account.

**Comment by drewbs-b** [comment]
I have completely uninstalled and reinstalled the app a couple times now and the issue persists - I generally only have a “home” feed the first time I use the app after an install.

**Comment by drewbs-b** [comment]
Actually after reading other issues I think this may be a symptom of the “soft logout” - I logged in again and got my home feed back
