### ISSUE TITLE
Crash on loading post

### ISSUE THREAD

**Issue by bjr70** [hariettem/Artemis#330]
**Describe the bug**
I'm logged in and was visiting a post I commented on earlier. It was trying to load the 20 comments when it crashed. Previously this evening it hung and I had to restart the app. This time it hung and then crashed. 

URL https://kbin.social/m/scifi/t/229353/shared-on-Artemis

**To Reproduce**
1. Open Artemis
2. Click on the link https://kbin.social/m/scifi/t/229353/shared-on-Artemis
3. While loading it crashed

**Expected behavior**
I expected it to load the thread. This is happening on multiple posts. It did say data was sent. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung A71 5G
 - OS: Android 13 / One UI 5.1
 - Version [e.g. alpha.1]

**Additional context**

**Comment by hariettem** [comment]
new api should fixed this
