### ISSUE TITLE
Text Formatting Shorcuts

### ISSUE THREAD

**Issue by omlettehead** [hariettem/Artemis#331]
**Is your feature request related to a problem? Please describe.**
When writing a comment, I often forget the code to include an embedded link or to format text styling. (Making a word italic or bold, etc.)

**Describe the solution you'd like**
Like on the Kbin web page or the Apollo app, I'd like to have text formatting buttons above the text field to make formatting text quick and easy.

**Describe alternatives you've considered**
Any simple means to quickly reference various types code that's used to format text so I can look it up and input it myself.

**Additional context**
N/A

**Comment by hariettem** [comment]
added!
