### ISSUE TITLE
Upvoting or boosting a comment goes back to the previous page

### ISSUE THREAD

**Issue by brinazarski** [hariettem/Artemis#333]
iPhone XR
iOS 16.5
Artemis version: 0.1.7
Update: 2307.19.23.54

I keep swiping from right to left to access the upvote/boost buttons, but it acts as if I’m swiping from left to right and brings me back to the previous page.

Currently I am on “all” with the top posts in the past day. This has happened on these two posts so far:

https://kbin.social/m/privacyguides@lemmy.one/t/237517/

https://kbin.social/m/piracy@lemmy.dbzer0.com/t/237858/

**Comment by hariettem** [comment]
swipe actions redone, reopen if still present
