### ISSUE TITLE
GIF in comments

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#34]
**Describe the bug**
If a user posts a comment containing just a GIF, the comment doesn't show anything in Artemis.

**To Reproduce**
1. Go to a comment with a gif
2. See error

**Expected behavior**
Expect gif to load and play in line with other comments. 

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/49291963/21521898-2a22-48d0-8a0c-573e9b247256)
![image](https://github.com/hariettem/Artemis/assets/49291963/74f48f06-35de-423c-ad27-56721eac63c7)
![image](https://github.com/hariettem/Artemis/assets/49291963/fcd14f82-2563-4960-a98d-f2771c4ec947)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: alpha.1

**Comment by hariettem** [comment]
added
