### ISSUE TITLE
Sidebar doesn't scroll all the way

### ISSUE THREAD

**Issue by thesoloist-1** [hariettem/Artemis#341]
**Describe the bug**
When the sidebar is scrollable, it doesn't scroll all the way down.

**Screenshots**
https://github.com/hariettem/Artemis/assets/97246028/a62fe27e-19ab-4fd7-b9fc-599f18e5c629

**Smartphone:**
 - Device: iPhone 12 Pro
 - OS: iOS 17 beta
 - Version Version: 0.2.0
Update: 2308.03.01.26
(12f9d09a-908c-4b9d-b922-c04ed5ab2514)}
Channel: preview

**Comment by its-yourmom** [comment]
Can confirm this bug on iOS iPhone 11 Pro version 16.1.1 newest update 2.0

**Comment by hariettem** [comment]
Fixed!
