### ISSUE TITLE
Authorization loop on public beta version (artemis.camp)

### ISSUE THREAD

**Issue by RheingoldRiver** [hariettem/Artemis#343]
**Describe the bug**
When attempting to authorize on artemis.camp, instead you are stuck on an infinite loop of "waiting for browser." But the "Allow" button in the browser doesn't work, and on closing or restarting the app, it just says "waiting for browser" over and over and over.

**To Reproduce**
1. Correctly type your username & pass
2. Be in the browser
3. Try to click accept
4. Notice it's unresponsive - yikes!
5. Close everything and restart
6. gg it just says "waiting for browser" forever now

**Expected behavior**
in step 3, you just clicked accept and it worked

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: [ssg 9]
 - OS: [andr 10]
 - Version [0.2]

**Additional context**
the splash on this page looks nice :)

**Comment by hyplex1** [comment]
This is happening to me as well, exactly thr same as described in the OP. The slight difference is sometimes I'm presented with a blank black screen when Artemis tries to redirect to Browser, instead of it saying I'm waiting on browser.

Android Galaxy s23, v 13

**Comment by hyplex1** [comment]
Clearing cache in android app settings for Artemis allowed me to properly authenticate

**Comment by RheingoldRiver** [comment]
Harriette fixed this! ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
