### ISSUE TITLE
Font customization

### ISSUE THREAD

**Issue by m3enzo** [hariettem/Artemis#35]
**Is your feature request related to a problem? Please describe.**
No, just an enhancement to UI configuration. 

**Describe the solution you'd like**
Be able to set custom font sizes. Sometimes fonts may be too small or too big so having an adjustable slider under display/general config would be helpful. Can also be useful for accommodating accessibility features related to fonts/readability.

**Comment by lvndr-dev** [comment]
Personally, I'd prefer getting the default settings right first. Select the typeface, size, and general feel of Artemis. Once that baseline is established, customization can be targeted.

**Comment by m3enzo** [comment]
Agreed, just something to have later down the line. Currently I think we're going down the right path, once we can have a cohesive look, this is something we should look into for future iterations.

**Comment by win8linux** [comment]
This could actually be useful for accessibility, since it would allow for dyslexics to use a more suitable font.

**Comment by Trez-zerT** [comment]
Including https://opendyslexic.org/ by default would be great in terms of accessibility.
