### ISSUE TITLE
Code text in a code font

### ISSUE THREAD

**Issue by LazaroFilm** [hariettem/Artemis#355]
Use a special font for code to make it easier to read. 
Bonus if it has ligatures. 
I like Monaco, Fira Code, or JetBrains Mono. 

This is the current font. Not easy to see what's code. 
![image](https://github.com/hariettem/Artemis/assets/18351100/ab143f78-b565-4278-9565-9c8605060e2e)

**Comment by RheingoldRiver** [comment]
I think this is a dupe of #460 - if I'm wrong, feel free to reopen
