### ISSUE TITLE
Preference: Large previews in compact view

### ISSUE THREAD

**Issue by RheingoldRiver** [hariettem/Artemis#358]
**Is your feature request related to a problem? Please describe.**
[See /kbin comment](https://kbin.social/m/fediverse/t/308610/Lemmy-and-Kbin-The-Best-Reddit-Alternatives#entry-comment-1408563)

* Personally, I think the previews are a good siz in compact mode
* Compact mode is supposed to be minimalist, and this is what you've made
* But there's been a complaint that the preview image thumbnails are too small, that compact mode isn't for minimalism, but for, well, simply compactness

**Describe the solution you'd like**
Add a setting: "Large previews in compact view"

* When enabled, this preference makes the thumbnails grow to take up as much room as possible
	* As possible is debatable. They should def be limited by the height of the line
	* Can they make the text to the left overflow?
		* Depends how hard this is to implement
		* This could be a setting that breaks the view on some people's smaller phones, and is only usable by tablet users & people with larger screens
		* But ideally it cannot do this, and is constrained only to the space it has
	* Honestly idk what css or js magic exists to do this

**Describe alternatives you've considered**
All explored above

**Additional context**
N/A

**Comment by NaturalHate** [comment]
Well, here's an example of the desktop compact mode, completely filling out the available space.
https://i.imgur.com/XZGw8vD.png

I would show how the same thread looks like in the app, but it does not even show up in the apps instance, but it feels like 50% of the size of it, pretty much the smallest I've seen compared to any Lemmy or Reddit app. There's a lot of space to the top & right side of the screen, and I assume the same amount of space is available towards the bottom & left. A certain amount of space of course is needed to not clash with the title but it doesn't have to be that big, as most words cause a line break anyway, and there's not really a reason not to fill up the space to the other side.
