### ISSUE TITLE
Extremely slow performance throughout the entire app.

### ISSUE THREAD

**Issue by NaturalHate** [hariettem/Artemis#361]
**Describe the bug**
Scrolling the main feed it slows down to a crawl, feeling like below 10 FPS. Scrolling comments within a thread is the same. Scrolling the settings page is the same. Sometimes it speeds up for a short moment but then it immediately slows down again.

**To Reproduce**
1. Scroll anywhere.

**Expected behavior**
Fluid performance.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 13
 - Version 0.2.0

**Comment by RheingoldRiver** [comment]
Hey @NaturalHate do you have any other fediverse-related apps open? I'm asking because someone else reported similar issues with EXTREMELY slow performance and then it turned out there was an "open links with Lemmy" app open in the background that was trying to read every single link in Artemis and causing it to work at almost a standstill.

(perf in Android in general is definitely a concern though, even if this case doesn't apply to you)

**Comment by NaturalHate** [comment]
> Hey @NaturalHate do you have any other fediverse-related apps open? I'm asking because someone else reported similar issues with EXTREMELY slow performance and then it turned out there was an "open links with Lemmy" app open in the background that was trying to read every single link in Artemis and causing it to work at almost a standstill.
> 
> (perf in Android in general is definitely a concern though, even if this case doesn't apply to you)

Not that I can tell. I have Infinity for Lemmy, Jerboa and Mastodon installed, but I typically just use kbin.social on the desktop for the most part and I typically swipe up to close any application after I'm done using them. Could this be somehow related to server performance? I noticed that the artemis.camp instance is also extremely slow on my end when I check it on the desktop.

**Comment by NaturalHate** [comment]
Actually, small bedtime update. The latest app update from today seems to have fixed it. I do now scroll often into empty spaces but it doesn't slow down anymore.

**Comment by RheingoldRiver** [comment]
Great to hear! Tysm for the update
