### ISSUE TITLE
Missing magazine sidebar description overflow gradient with Pure Black

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#377]
**Describe the bug**
A gradient at the bottom of the magazine sidebar description in the magazine view does not show up when Pure Black setting is enabled.

**To Reproduce**
1. Go to Settings tab
2. Set Theme Mode to 'dark' (unless dark theme mode is set by the system already)
3. Enable Pure Black setting
4. Go to Home tab
5. Go to a magazine
6. See overlapping text of the shortened magazine sidebar description and 'Open sidebar' button where a gradient should be

**Expected behavior**
A gradient is shown near the 'Open sidebar' button

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/11584387/cf74c719-f5df-4e83-92e5-991f05e6653b)
> Correct behavior with a regular dark theme

![image](https://github.com/hariettem/Artemis/assets/11584387/4f9f1dd5-c110-44e1-928f-4bd60e5f13af)
> Incorrect behavior with a pure black dark theme

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 15.7.6
 - Version: 0.2.0
 - Update: 2308.10.03.08
(0dc5e1d6-0cf6-4368-9634-4f4210288fe8)}
 - Channel: preview

**Comment by hariettem** [comment]
fixed pushed rn
