### ISSUE TITLE
Tapping a tagged user does not bring you to their profile page

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#383]
**Describe the bug**
If a user is tagged in the comments, tapping their name takes you to a broken splash screen.

**To Reproduce**
1. Go to the comments or a post with someone tagged.
2. Click on the tagged user
3. See error

**Expected behavior**
The users profile page to load, similarly to how it loads if you tap on someone's profile picture.

**Screenshots**
https://github.com/hariettem/Artemis/assets/49291963/5ad79766-71ad-4e43-bdd8-dee059d1013a

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.6
 - Version: 0.2.0
Update: 2308.11.20.48
(cb4e08a1-6111-42d4-92d9-1a43ea25cae8)}
Channel: preview

**Comment by hariettem** [comment]
just pushed a fix for this, should be up in five
