### ISSUE TITLE
Access more thread when replying.

### ISSUE THREAD

**Issue by omlettehead** [hariettem/Artemis#386]
**Is your feature request related to a problem? Please describe.**
When a discussion can span several days, it can be easy to lose track of the point of the discussion. When the only context you can reference while typing is the comment you are directly replying to, it becomes really easy to get derailed or even gaslit. I believe it would be beneficial for discourse to be able to view the entire discussion when drafting replies.

**Describe the solution you'd like**
The ability to scroll up from the comment you're replying to in order to view prior comments connected to the discussion.

**Describe alternatives you've considered**
The ability to temporarily hide the reply window to view the thread as normal could suffice.

**Additional context**
N/A

**Comment by RheingoldRiver** [comment]
@omlettehead I am not sure if this is already WIP, need to find out from Hariette, that's why "more info needed"

**Comment by omlettehead** [comment]
> @omlettehead I am not sure if this is already WIP, need to find out from Hariette, that's why "more info needed"

I realize now the current app is allowing me to drag down to hide the reply box to view the thread. I'm not sure if this is a recent update or I just didn't check correctly the first time. I apologize. Still, if I'm replying to a direct message in my inbox and tap to view the whole thread, everything I've typed up to that point goes away. That probably counts as a separate issue though.

**Comment by RheingoldRiver** [comment]
Ah great, yeah, can you open a new ticket for that?
