### ISSUE TITLE
Thumbnails are distorted with wrong aspect ratio

### ISSUE THREAD

**Issue by m3enzo** [hariettem/Artemis#41]
**Describe the bug**
In the current posts view, thumbnail images that are not square (1:1) are not scaled/cropped making the thumbnail look squished. 

**To Reproduce**
1. Go to posts view
2. See issue on posts with thumbnails 

**Expected behavior**
Images should be cropped using the shortest axis to fill the thumbnail space but maintain its aspect ratio. 

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/137343614/97a6de5e-51f7-4948-8c99-13735882e3b5)
![image](https://github.com/hariettem/Artemis/assets/137343614/7a93ebdb-3ec3-4d7f-aa80-db66f3a6c01f)

**Comment by hariettem** [comment]
This is a bug with kbin... they actually distort the thumbnail when they generate it......
