### ISSUE TITLE
Magazine sorting is not working

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#47]
**Describe the bug**
Attempting to change the sorting of a magazine does not do anything.

**To Reproduce**
1. Go to a magazine
2. Change the sorting from **Hot** to something else
3. See error

**Expected behavior**
The sorting to change, assumingly based on the kbin sorting algorithm.

**Screenshots**
https://github.com/hariettem/Artemis/assets/49291963/c3cf67ba-fe06-4045-8698-1b12b316aedd

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: alpha.2

**Additional context**
The same behavior is shown on /m/Home.

**Comment by hariettem** [comment]
Fixed it on the backend :)
