### ISSUE TITLE
Something to indicate pinned posts

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#49]
**Is your feature request related to a problem? Please describe.**
Say you sort a magazine by new, there might still be a couple posts at the top that are old, they're likely just pinned posts. Something to indicate that they're pins would be nice!

**Describe the solution you'd like**
Maybe a little pin next to the post or author of the post with a green color.

**Additional context**
In the screenshot, I am sorted by new, which is working correctly. But, the top post is older, that's because it is a pinned post within the magazine.
![image](https://github.com/hariettem/Artemis/assets/49291963/ac6da20d-c4a5-4c06-9d77-43d1f9d3b9b5)

**Comment by hariettem** [comment]
Last night I was browsing a magazine w a few of em and was thinking the same thing!
