### ISSUE TITLE
Refreshing a magazine causes posts to duplicate.

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#5]
**Describe the bug**
Refreshing a magazine causes the posts to duplicate, this occurs ad nauseum and is only an issue in magazines with less than a full page of posts.

**To Reproduce**
1. Go to a magazine, for example /m/ArtemisApp
2. Pull down to refresh
3. Posts duplicate

**Expected behavior**
Posts upvotes/boosts/comment count will update to the latest value.

**Screenshots**
https://github.com/hariettem/Artemis/assets/49291963/32dda0ab-72b5-46d3-afcd-8003ce35c095

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version alpha.1

**Additional context**
Reproducibility: This behavior occurs 10/10 times, at least on magazines with one page or less.
[This might be related to issue #24!](https://github.com/hariettem/Artemis/issues/24#issue-1772428319)

**Comment by lvndr-dev** [comment]
Reproducible on iPhone Xs Max.
Along with the duplication, notice [the spinner appearing twice.](https://files.catbox.moe/bvddhp.png)
