### ISSUE TITLE
Refreshing while vote still processing. Should block..?

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#54]
**Describe the bug**
Basically the title. If you upvote a post from community view, the vote count is not updated unless you initiate a refresh.

**To Reproduce**
1. Go to any magazine or community
2. Upvote or downvote a post from community view
3. See error

**Expected behavior**
Similar behavior to voting on comments, the votes to update accordingly. IE: x + 1 for upvotes or x - 1 for downvotes. 

**Screenshots**
https://github.com/hariettem/Artemis/assets/49291963/bd6fb335-89e3-4675-872f-90103b312ced

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: alpha.2

**Comment by hariettem** [comment]
issue is the delay in vote going through... not sure we can do much till after api.

Looks like apollo blocks refreshes when waiting on votes..
