### ISSUE TITLE
Blue icon with arrow overlaps content and content is cut off on scroll

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#58]
**Describe the bug**
Blue icon with arrow overlaps comments on post with few replies. 
Pulling down to scroll leads to cropping. 

**To Reproduce**
1. Go to low interaction post
2. Arrow is present and overlaps content. 
3. Scroll down. 
4. See crop. 

**Screenshots**

![image](https://github.com/hariettem/Artemis/assets/83763643/495a8185-a78a-41ed-8a89-49d84d795184)

![image](https://github.com/hariettem/Artemis/assets/83763643/4ea388e4-3e98-4186-bec2-e7aa0f78381f)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs max. Latest iOS. 

**Additional context**

**Comment by hariettem** [comment]
fixed!
