### ISSUE TITLE
Delayed/discarded post actions

### ISSUE THREAD

**Issue by win8linux** [hariettem/Artemis#6]
**Describe the bug**
When initiating a post action (i.e. boosting, favoriting, etc.), it may either be delayed or discarded entirely.

**To Reproduce**
1. Go to a post
2. Tap on a post action (favorite, boost, etc.)
3. Wait a couple seconds

**Expected behavior**
Post action is carried out immediately without reverting back momentarily or completely.

**Screenshots/Recordings**

https://github.com/hariettem/Artemis/assets/11584387/d4f85127-6a91-41ac-bc40-deb86bf93d37

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 15.7.6
 - Version: alpha.1

**Additional context**
Issue can be quite inconsistent to replicate. Network conditions may be a testing factor.

**Comment by hariettem** [comment]
Fixed by blocking and showing a waiting indicator on prior action
