### ISSUE TITLE
Swipe areas too small / conflicting with other interactions.

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#61]
**Describe the bug**
Swipe margins for back and forward are either too small, or are not detected properly.

**Comment by justinferrell** [comment]
Ran into this as well. iPhone 14, couldn't swipe back to home from a magazine using thumb on left edge.

**Comment by justinferrell** [comment]
Confirmed this happens in webviews loaded from links in comments too. Couldn't swipe back, had to tap "done"

**Comment by hariettem** [comment]
fixed
