### ISSUE TITLE
Following a community does not update follow list until app is killed and reopened

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#63]
**Describe the bug**
Both following and unfollowing a community does not update your follow list in app unless the app is killed.

**To Reproduce**
1. Go to a community
2. Click on the `+` or `-`
3. Navigate to your following magazines by tapping the current community name

Once you kill the app and reopen it, your follows will be updated and appearing correctly.

**Expected behavior**
For the follow list to update accordingly on follow/unfollow

**Screenshots**
https://github.com/hariettem/Artemis/assets/49291963/66d06e17-5fa0-48fe-827a-82ba9f68e17d

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: 0.1.2

**Comment by RheingoldRiver** [comment]
Happens on Android too, see #66 (closed as dupe)

**Comment by hariettem** [comment]
We're clearing the network cache, just not telling the list to reload. Let me think about a good way to go about fixing this.
