### ISSUE TITLE
When you subscribe to a new magazine on pc, you have to force-reopen the app for it to show in search

### ISSUE THREAD

**Issue by RheingoldRiver** [hariettem/Artemis#66]
**Describe the bug**
Simply refreshing the home screen isn't enough to reload your subbed magazines, but it should be

**To Reproduce**
1. Open Artemis
2. On PC, sub to a new magazine
3. Refresh the Artemis homescreen
4. Open search
5. Observe your new magazine isn't there

**Expected behavior**
Your new magazine should be there

**Screenshots**
Can't really show this

**Smartphone (please complete the following information):**
 - Device: SSG 9
 - OS: Android 10
 - Version 0.1.2

**Additional context**
* Possibly, this should wait until the kbin api exists if fetching subbed magazines is very slow atm
* If fetching subbed magazines gets faster, it should happen in the background when you reopen the app after a long time idle, or when you open search, or something, i.e. not making the manual refresh required

**Comment by kruggiero97** [comment]
Similar behavior is exhibited on iOS when you sub via the Artemis App. See [#63](https://github.com/hariettem/Artemis/issues/63)

**Comment by RheingoldRiver** [comment]
ah thanks, ill close this and add a comment there
