### ISSUE TITLE
Preload Posts in Lists

### ISSUE THREAD

**Issue by justinferrell** [hariettem/Artemis#73]
**Is your feature request related to a problem? Please describe.**
Opening posts from a list seems to call the API when you tap right now, so you have to wait for a second while it makes the API call. 

**Describe the solution you'd like**
Fetching some number of posts when a list appears could catch most clicks and make the loading feel instant. 

**Describe alternatives you've considered**
It's probably way too early for this kind of optimization but wanted to flag it. I know Apollo did it this way because Christian referenced it as a way to maybe reduce API calls.

**Comment by hariettem** [comment]
>Fetching some number of posts when a list appears

is list here talking about the community/magazine list? Like fetching some posts from each of you subscriptions?

**Comment by justinferrell** [comment]
I was thinking of when opening a post from a magazine. So imagine you open a magazine and you're presented with a list of posts. Before you tap any, preload the top 5 or 10 (however many) in the background so that if/when they are tapped, they appear instantly.
