### ISSUE TITLE
Display of / interaction with images

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#75]
**Describe the bug**
Interacting with images is not smooth, or swipe areas are not where expected. 

**To Reproduce**
Tap to open image. 
Attempt to swipe image away from transparent overlay, or from its edges. 
Image either does not react, or does not move as expected. 

**Expected behavior**
Transparency suggests being able to tap on overlay to close image. Swiping should be more lenient/reactive. 

**Screenshots**

https://github.com/hariettem/Artemis/assets/83763643/c991b562-f3d8-4c38-91b6-e5f75f2f0c99

Apollo interaction example:
https://github.com/hariettem/Artemis/assets/83763643/5604f5b7-95c2-4a64-807d-772c5a5b1b62

**Smartphone (please complete the following information):**
iPhone XS max latest iOS. 

**Additional context**
Suggestion: instead of transparent, overlay could be black. This dispels ambiguity of means of interaction.

**Comment by hariettem** [comment]
Need to rewrite that whole section. #28 complained about it too

**Comment by hiimmike** [comment]
In addition to sometime being unable to open or dismiss and image, I have experienced some slight, but noticeable lag when clicking to open / swiping to close images when they do open.

**Comment by hariettem** [comment]
fixed
