### ISSUE TITLE
Indicate when a post has been read or viewed

### ISSUE THREAD

**Issue by zero-yeliad** [hariettem/Artemis#76]
**Describe the solution you'd like**
Currently, if you are scrolling through posts in a community, there is no way to show if you have already read or viewed the post. Other apps have adopted a way of dimming the titles of viewed posts to show it has been opened before. This method seems most intuitive.

**Describe alternatives you've considered**

- Hiding the post when read, so it doesn't show up while scrolling through the same community. Perhaps that could be a toggled in settings later down the line, since that might be frustrating by default.
- An icon or symbol next to the title. Although, this could get messy if there are too many elements near each other.

**Comment by lvndr-dev** [comment]
Ui/ux wise - dimming the typeface might be the best option going forward. 

An icon would add clutter. 

Hiding posts on read should be an appearance option.

**Comment by lvndr-dev** [comment]
![image](https://github.com/hariettem/Artemis/assets/83763643/718928e6-d290-4b9e-a2bc-de2c47a15a2a)

Example

**Comment by pvmzqahgyd** [comment]
I recall Apollo having several settings for that. There was an option to automatically mark posts as read as you scroll through, or only mark if there is an interaction. Memmy for example has the toggles to mark as read if you open post, view image, or vote (each is a toggle). Apollo also had the option of hiding read posts by using the menu on top right, or you could enable a "hire read posts" button that floated on bottom right.

**Comment by Alaric323** [comment]
Sync for Reddit (Android) had exactly this, where it dimmed the text (unless it was a megathread/mod post) and faded a preview image.  It worked well in my opinion.

**Comment by hariettem** [comment]
Done. For more options, like on scroll and whatnow, please file another ticket
