### ISSUE TITLE
Quick Swipe to vote

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#82]
**Is your feature request related to a problem? Please describe.**
I am not a fan of interactions that are staggered in steps while they could be one swipe. Up/Down voting comes to mind.

**Describe the solution you'd like**
Swipe left from right edge on post for 15% of the width to quickly upvote. Swipe 30% to downvote. Swipe from left edge to 15% to boost. Swipe to 30% to reply. Haptic feedback notifies user of interaction. Directions can be flipped if desired. Subject of interaction can be post, comment, microblog etc. 

**Describe alternatives you've considered**
Long presses for accessibility. 

**Additional context**

https://github.com/hariettem/Artemis/assets/83763643/e45a7de8-70cc-47fe-8202-9664bd23cce7

**Comment by SARankDirector-Minecraft** [comment]
There is a UX issue with most swipe gestures like this, where you don’t know what does what, however I agree that swipe gestures like this is the way to go

**Comment by SARankDirector-Minecraft** [comment]
this is what I was thinking

![image](https://github.com/hariettem/Artemis/assets/16199488/413ab63e-e982-42b9-85ff-792ae5972700)

**Comment by hariettem** [comment]
pls open new ticker for fancier options of this feature :)
