### ISSUE TITLE
pull-refresh may not be working properly?

### ISSUE THREAD

**Issue by RheingoldRiver** [hariettem/Artemis#88]
**Describe the bug**
kbin is down right now, but I pull-refreshed and everything is still there, so it may not be pinging the server properly.

Or, maybe kbin being down is a local issue? idk.

**To Reproduce**
1. Wait for kbin to be down
2. Pull-refresh the app
3. Observe that the posts are still there

**Expected behavior**
Until #87 is implemented, everything should go away / a notice about connectivity should be shown

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: SSG 9
 - OS: Android 10
 - Version 0.1.2

**Additional context**
Discord discussion link: https://discord.com/channels/1118996335119569036/1121160642146078760/1124115981862719549

**Comment by hariettem** [comment]
fixed for next update
