### ISSUE TITLE
Comments in thread overflows window

### ISSUE THREAD

**Issue by thesoloist-1** [hariettem/Artemis#90]
**Description:**
FYI this does not occur on every post but some comments in a comment tree are not always overflowing correctly and is causing deeper level comments to overlap the window. Refreshing the page or restarting the app does not fix the issue.

The default font size is selected and occurs on both non bold and bold font selection in Apple settings.

![image](https://github.com/hariettem/Artemis/assets/97246028/2175a576-96b3-4090-a38b-aa1781dd85fc)

 - Phone [iPhone12 Pro]
 - OS [iOS 17 beta]

**Comment by hariettem** [comment]
fixed in next build
