### ISSUE TITLE
Can't swipe up to dismiss image

### ISSUE THREAD

**Issue by justinferrell** [hariettem/Artemis#91]
**Describe the bug**
After tapping the thumbnail for an image post and viewing the image that appears (with the black, half opacity background) you can't swipe up on the image. You have to swipe down on the image. 

**To Reproduce**
1. Go to a list of posts, like a magazine
2. Click on the thumbnail for an image post 
3. Try to dismiss it by swiping up

**Expected behavior**
It feels like the image should swipe away freely, in any direction, like Ivory/Tweetbot

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/1128985/56058af7-bb19-490c-a6af-00b56ae71feb)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16

**Comment by justinferrell** [comment]
This is honestly more of an enhancement than a bug. I don't think I can change the label in the GitHub app though.

**Comment by kruggiero97** [comment]
> This is honestly more of an enhancement than a bug. I don't think I can change the label in the GitHub app though.

I gotchu ;)

**Comment by lvndr-dev** [comment]
I've made note of similar here: #75

Might be a duplicate issue!

**Comment by justinferrell** [comment]
Yeah, this is a dupe. This can be closed. Thanks!

**Comment by hariettem** [comment]
Closing as dupe! Will fix with #75
