### ISSUE TITLE
Ambiguous timestamp format

### ISSUE THREAD

**Issue by zero-yeliad** [hariettem/Artemis#92]
When viewing a post that has the timestamp of "1m", I thought it meant one minute ago, not one month. Apollo uses "mo" to denote month. 

Artemis:
![image](https://github.com/hariettem/Artemis/assets/5020168/478a5028-c926-439e-9f84-21987966df58)

Apollo:
![image](https://github.com/hariettem/Artemis/assets/5020168/7a317900-7035-4415-bf8a-a0e5be926bf0)

Solution:
Reformatting month time stamp from "m" to "mo" for less ambiguity.

**Comment by hariettem** [comment]
fixed
