### ISSUE TITLE
Exit the sort by menu by interacting anywhere outside the sort menu

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#95]
**Is your feature request related to a problem? Please describe.**
At the moment the only way to exit the sort by menu is to interact again with the symbol for how you are sorting (fire (hot), stars (new), top (trophy))or by selecting a sorting option. The app will allow you to scroll while the menu is still up. Interacting with a post while the menu is still up will show you the post without the menu but when you go back you will see the previous screen with the menu still up. 

**Describe the solution you'd like**
I would like to see the sort by menu close if you interact anywhere outside of it. If I scroll with the menu up it should close. If I interact with a post while the menu is up and then back out of the post the menu should remain closed. 

**supporting video**
https://github.com/hariettem/Artemis/assets/138167591/f37fe6bc-b677-49d7-871c-2c3fecab6613

**Comment by Alaric323** [comment]
This is a good idea.  Even if you open another magazine and come back to all, the menu is still showing.

**Comment by hariettem** [comment]
fixed
