### ISSUE TITLE
Clicked link causes Artemis to crash

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#97]
**Describe the bug**
I found a link that when clicked causes Artemis to crash. The same link was posted after in the same thread and has the link preview box while the one that causes the crash is missing the preview box. 

**To Reproduce**
1. Go to [this](https://kbin.social/m/privacyguides@lemmy.one/t/111280/shared-on-Artemis) thread
2. Go to the comment thread started by Matricaria. Click the link in his comment to 0x0.st
3. You should see Artemis crash

**Expected behavior**
You should be able to click the link and view the webpage with the in-app browser

**Video**
https://github.com/hariettem/Artemis/assets/138167591/a8790219-c4aa-41ca-abf9-3f2c5c9ad72e

**Smartphon:**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16
 

**Additional context**
On a normal browser the link is still clickable but if clicked seems to link back to the thread. Likely is a formatting error that is causing Artemis to crash.

**Comment by lvndr-dev** [comment]
Had similar crash happen. 

![image](https://github.com/hariettem/Artemis/assets/83763643/c6f5bbd5-0dc3-4ed4-81e2-43df262bbc5f)

Can't screen record, crash also kills recording session. 

https://kbin.social/m/kbinMeta/t/138262 link in question. 

Video in post is displayed on kbin but not in app. 
Crash seems to linger. Trying to copy the url from within artemis makes the app crash, and will also crash github app when attempting to paste.

**Comment by lvndr-dev** [comment]
Addition: after crash, the next external link you click upon reopening, crashes the app again. After this, the app seems to be functioning normally again.

**Comment by ex-youth** [comment]
Seeing a crash upon clicking any of the links in this post (can replicate):

https://kbin.social/m/fediverse@lemmy.world/t/131427/shared-on-Artemis




Version: 0.1.7

Update: 2307.10.16.09
(48a656f7-be5b-4f05-be33-069824ef1049)}
