### ISSUE TITLE
Tap option title for extra info

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#98]
**Is your feature request related to a problem? Please describe.**
As clear and concise option titles may be, they can still be ambiguous enough to be open to interpretation. 

**Describe the solution you'd like**
Rather than having to create a video preview for every option (and update those whenever the app changes visually) a simple tap of the item text could show a popup with a short explanation. 

**Describe alternatives you've considered**
Video/image of the option in action. While a great idea, it might be troublesome down the line in regards to keeping the app up to date. It might also lead to filesize bloat. 

**Additional context**
https://github.com/hariettem/Artemis/assets/83763643/4bec7ee7-54b7-4f0e-9bc0-d291dbd9ec05

**Comment by lvndr-dev** [comment]
... I missed River's post #93  because the page hadn't refreshed.

**Comment by RheingoldRiver** [comment]
I copied this post into #93 and I'm gonna close this one to avoid having duplicates
